plugins {
  id 'com.google.protobuf' version '0.10.0'
}

apply from: "$rootDir/gradle/java.gradle"

addTestSuiteForDir('latestDepTest', 'test')

def grpcVersion = '1.42.2'

muzzle {
  pass {
    group = 'io.grpc'
    module = 'grpc-core'
    versions = '[1.5.0,)'
    assertInverse = true
  }
}

dependencies {
  compileOnly group: 'io.grpc', name: 'grpc-core', version: grpcVersion

  testImplementation group: 'io.grpc', name: 'grpc-core', version: grpcVersion
  testImplementation group: 'io.grpc', name: 'grpc-netty', version: grpcVersion
  testImplementation group: 'io.grpc', name: 'grpc-protobuf', version: grpcVersion
  testImplementation group: 'io.grpc', name: 'grpc-stub', version: grpcVersion
  testImplementation group: 'javax.annotation', name: 'javax.annotation-api', version: '1.3.2'

  latestDepTestImplementation group: 'io.grpc', name: 'grpc-core', version: '1.+'
  latestDepTestImplementation group: 'io.grpc', name: 'grpc-netty', version: '1.+'
  latestDepTestImplementation group: 'io.grpc', name: 'grpc-protobuf', version: '1.+'
  latestDepTestImplementation group: 'io.grpc', name: 'grpc-stub', version: '1.+'
}

def protocVersion = '3.17.3'
// aarch_64 support was added in 3.17.3
def protocArch = System.getProperty("os.arch") == "aarch64" ? ":osx-x86_64" : ""
def grpcArch = System.getProperty("os.arch") == "aarch64" ? ":osx-x86_64" : ""

protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:${protocVersion}${protocArch}"
  }
  plugins {
    grpc {
      artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}${grpcArch}"
    }
  }
  generateProtoTasks {
    ofSourceSet("test").configureEach {
      plugins {
        grpc {}
      }
    }
  }
}
