plugins {
  id 'scala'
  id 'dd-trace-java.module.internal-library'
}

dependencies {
  implementation group: 'org.scala-lang', name: 'scala-compiler', version: '2.13.3'
}

tasks.withType(ScalaCompile).configureEach {
  // Scala compilers here can't run on modern JDKs; pinned to JDK 8.
  // * https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
  configureCompiler(it, 8, JavaVersion.VERSION_1_8, "Scala compilers here do not run on modern JDKs")
}
