/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2024-04-25 10:32:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package datadog.trace.agent.tooling.iast.stratum;

import java.io.PrintWriter;
import java.io.Writer;
import javax.servlet.*;
import javax.servlet.http.*;

public final class IndexJsp {

  private static java.util.Map<String, Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<String, Long>(2);
    _jspx_dependants.put("/WEB-INF/tlds/hdiv-c.tld", Long.valueOf(1709715080729L));
    _jspx_dependants.put("/WEB-INF/jsp/template/tags.jsp", Long.valueOf(1709715080729L));
  }

  public java.util.Map<String, Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {}

  public void _jspDestroy() {}

  public void _jspService(final HttpServletRequest request, final HttpServletResponse response)
      throws java.io.IOException, ServletException {

    Writer out = null;

    response.setContentType("text/html");
    out = new PrintWriter(response.getWriter());

    out.write("<!DOCTYPE html>\n");
    out.write("\n");
    out.write("\n");
    out.write("\n");
    out.write("\n");
    out.write("\n");
    out.write("\n");
    out.write("<html>\n");
    out.write("<head>\n");
    out.write("<title>Hdiv Spring Mvc Examples</title>\n");
    out.write("</head>\n");
    out.write("<body>\n");
    out.write("\t");
    out.write("\n");
    out.write("</body>\n");
    out.write("</html>\n");
  }
}
