plugins {
  id 'dd-trace-java.module.smoke-test'
  id 'dd-trace-java.testcontainers'
}

dependencies {
  testContainerImage(image('icr.io/appcafe/websphere-traditional:latest', 'test.websphere.image'))

  testImplementation project(':dd-smoke-tests')
  testImplementation libs.testcontainers
}

testJvmConstraints {
  // there is no need to run it multiple times since it runs on a container
  minJavaVersion = JavaVersion.VERSION_25
  maxJavaVersion = JavaVersion.VERSION_25
}

tasks.withType(Test).configureEach {
  usesService(testcontainersLimit)
}
