#!/usr/bin/env bash

jar_command="jar"
jar_file="unknown.jar"

while [[ $# -gt 0 ]]; do
  case $1 in
    --command)
      jar_command="$2"
      shift # past argument
      shift # past value
      ;;
    --file)
      jar_file="$2"
      shift # past argument
      shift # past value
      ;;
    *)
      echo "Unknown option $1"
      exit 1
      ;;
  esac
done

# Check that all the expected contents is there
while IFS= read -r line;
do
  ${jar_command} tf "${jar_file}" | grep -q -E "${line}"
  if [ $? -ne 0 ]; then
    echo "ERROR: Unable to find content matching '${line}' in jar file ${jar_file}"
    exit 1
  fi
done < expected_jar_contents.txt

# Check that there is no unexpected content
extra_contents=$(${jar_command} tf "${jar_file}" | grep -v -E -f expected_jar_contents.txt)
if [ ! -z "${extra_contents}" ]; then
  echo "ERROR: Found unexpected contents in jar file:"
  echo "$extra_contents"
  exit 1
fi
