pluginManagement {
  repositories {
    mavenLocal()

    if (settings.extra.has("gradlePluginProxy")) {
      maven {
        url = uri(settings.extra["gradlePluginProxy"] as String)
        isAllowInsecureProtocol = true
      }
    }
    if (settings.extra.has("mavenRepositoryProxy")) {
      maven {
        url = uri(settings.extra["mavenRepositoryProxy"] as String)
        isAllowInsecureProtocol = true
      }
    }
    gradlePluginPortal()
    mavenCentral()
  }
}

plugins {
  id("com.gradle.develocity") version "4.1"
}

val isCI = providers.environmentVariable("CI")
val skipBuildscan = providers.environmentVariable("SKIP_BUILDSCAN").map { it.toBoolean() }.orElse(false)

develocity {
  buildScan {
    termsOfUseUrl = "https://gradle.com/help/legal-terms-of-use"
    termsOfUseAgree = "yes"
    publishing.onlyIf { isCI.isPresent && !skipBuildscan.get() }
  }
}

// Don't pollute the dependency cache with the build cache
if (isCI.isPresent) {
  buildCache {
    local {
      directory = File(rootDir, "workspace/build-cache")
    }
  }
}

rootProject.name = "dd-trace-java"

// external apis
include(
  ":dd-trace-api",
  ":dd-trace-ot",
  ":dd-trace-ot:correlation-id-injection",
)

// agent projects
include(
  ":internal-api",
  ":internal-api:internal-api-9",
  ":dd-trace-core",
  ":dd-java-agent",
  ":dd-java-agent:agent-bootstrap",
  ":dd-java-agent:agent-builder",
  ":dd-java-agent:agent-tooling",
  ":dd-java-agent:agent-jmxfetch",
  ":dd-java-agent:agent-logging",
  ":dd-java-agent:agent-logs-intake",
  ":dd-java-agent:load-generator",
)

// profiling
include(
  ":dd-java-agent:agent-profiling",
  ":dd-java-agent:agent-profiling:profiling-ddprof",
  ":dd-java-agent:agent-profiling:profiling-controller",
  ":dd-java-agent:agent-profiling:profiling-controller-jfr",
  ":dd-java-agent:agent-profiling:profiling-controller-jfr:implementation",
  ":dd-java-agent:agent-profiling:profiling-controller-ddprof",
  ":dd-java-agent:agent-profiling:profiling-controller-openjdk",
  ":dd-java-agent:agent-profiling:profiling-controller-oracle",
  ":dd-java-agent:agent-profiling:profiling-testing",
  ":dd-java-agent:agent-profiling:profiling-uploader",
  ":dd-java-agent:agent-profiling:profiling-utils",
)

include(
  ":dd-java-agent:agent-debugger:debugger-bootstrap",
  ":dd-java-agent:agent-debugger:debugger-test-scala",
  ":dd-java-agent:agent-debugger:debugger-el",
)

include(
  ":dd-java-agent:agent-crashtracking",
  ":dd-java-agent:ddprof-lib",
)

include(
  ":dd-java-agent:agent-otel:otel-bootstrap",
  ":dd-java-agent:agent-otel:otel-shim",
  ":dd-java-agent:agent-otel:otel-tooling",
)

include(
  ":communication",
  ":components:context",
  ":components:environment",
  ":components:json",
  ":components:yaml",
  ":telemetry",
  ":remote-config:remote-config-api",
  ":remote-config:remote-config-core",
)

include(
  ":dd-java-agent:appsec",
)

// ci-visibility
include(
  ":dd-java-agent:agent-ci-visibility",
)

// llm-observability
include(
  ":dd-java-agent:agent-llmobs",
)

// iast
include(
  ":dd-java-agent:agent-iast",
)

include(
  ":dd-java-agent:cws-tls",
)

// misc
include(
  ":dd-java-agent:testing",
  ":utils:container-utils",
  ":utils:socket-utils",
  ":utils:test-agent-utils:decoder",
  ":utils:test-utils",
  ":utils:time-utils",
  ":utils:version-utils",
)

// smoke tests
include(
  ":dd-smoke-tests:apm-tracing-disabled",
  ":dd-smoke-tests:armeria-grpc",
  ":dd-smoke-tests:backend-mock",
  ":dd-smoke-tests:cli",
  ":dd-smoke-tests:concurrent:java-8",
  ":dd-smoke-tests:concurrent:java-21",
  ":dd-smoke-tests:crashtracking",
  ":dd-smoke-tests:custom-systemloader",
  ":dd-smoke-tests:dynamic-config",
  ":dd-smoke-tests:field-injection",
  ":dd-smoke-tests:gradle",
  ":dd-smoke-tests:grpc-1.5",
  ":dd-smoke-tests:java9-modules",
  ":dd-smoke-tests:jersey",
  ":dd-smoke-tests:jersey-2",
  ":dd-smoke-tests:jersey-3",
  ":dd-smoke-tests:jboss-modules",
  ":dd-smoke-tests:kafka-2",
  ":dd-smoke-tests:kafka-3",
  ":dd-smoke-tests:lib-injection",
  ":dd-smoke-tests:log-injection",
  ":dd-smoke-tests:maven",
  ":dd-smoke-tests:opentracing",
  ":dd-smoke-tests:opentelemetry",
  ":dd-smoke-tests:osgi",
  ":dd-smoke-tests:play-2.4",
  ":dd-smoke-tests:play-2.5",
  ":dd-smoke-tests:play-2.6",
  ":dd-smoke-tests:play-2.7",
  ":dd-smoke-tests:play-2.8",
  ":dd-smoke-tests:play-2.8-otel",
  ":dd-smoke-tests:play-2.8-split-routes",
  ":dd-smoke-tests:profiling-integration-tests",
  ":dd-smoke-tests:quarkus",
  ":dd-smoke-tests:quarkus-native",
  ":dd-smoke-tests:sample-trace",
  ":dd-smoke-tests:ratpack-1.5",
  ":dd-smoke-tests:resteasy",
  ":dd-smoke-tests:rum",
  ":dd-smoke-tests:rum:tomcat-9",
  ":dd-smoke-tests:rum:tomcat-10",
  ":dd-smoke-tests:rum:tomcat-11",
  ":dd-smoke-tests:rum:wildfly-15",
  ":dd-smoke-tests:spring-boot-3.0-native",
  ":dd-smoke-tests:spring-boot-2.4-webflux",
  ":dd-smoke-tests:spring-boot-2.5-webflux",
  ":dd-smoke-tests:spring-boot-2.6-webflux",
  ":dd-smoke-tests:spring-boot-2.7-webflux",
  ":dd-smoke-tests:spring-boot-3.0-webflux",
  ":dd-smoke-tests:spring-boot-2.3-webmvc-jetty",
  ":dd-smoke-tests:spring-boot-2.6-webmvc",
  ":dd-smoke-tests:spring-boot-3.0-webmvc",
  ":dd-smoke-tests:spring-boot-3.3-webmvc",
  ":dd-smoke-tests:spring-boot-rabbit",
  ":dd-smoke-tests:spring-security",
  ":dd-smoke-tests:springboot",
  ":dd-smoke-tests:springboot-freemarker",
  ":dd-smoke-tests:springboot-grpc",
  ":dd-smoke-tests:springboot-java-11",
  ":dd-smoke-tests:springboot-java-17",
  ":dd-smoke-tests:springboot-jetty-jsp",
  ":dd-smoke-tests:springboot-jpa",
  ":dd-smoke-tests:springboot-mongo",
  ":dd-smoke-tests:springboot-openliberty-20",
  ":dd-smoke-tests:springboot-openliberty-23",
  ":dd-smoke-tests:springboot-thymeleaf",
  ":dd-smoke-tests:springboot-tomcat",
  ":dd-smoke-tests:springboot-tomcat-jsp",
  ":dd-smoke-tests:springboot-velocity",
  ":dd-smoke-tests:tracer-flare",
  ":dd-smoke-tests:vertx-3.4",
  ":dd-smoke-tests:vertx-3.9",
  ":dd-smoke-tests:vertx-3.9-resteasy",
  ":dd-smoke-tests:vertx-4.2",
  ":dd-smoke-tests:wildfly",
  ":dd-smoke-tests:appsec",
  ":dd-smoke-tests:appsec:spring-tomcat7",
  ":dd-smoke-tests:appsec:springboot",
  ":dd-smoke-tests:appsec:springboot-grpc",
  ":dd-smoke-tests:appsec:springboot-graphql",
  ":dd-smoke-tests:appsec:springboot-security",
  ":dd-smoke-tests:debugger-integration-tests",
  ":dd-smoke-tests:datastreams:kafkaschemaregistry",
  ":dd-smoke-tests:iast-propagation",
  ":dd-smoke-tests:iast-util",
  ":dd-smoke-tests:iast-util:iast-util-11",
  ":dd-smoke-tests:iast-util:iast-util-17",
  // TODO this fails too often with a jgit failure, so disable until fixed
  // ":dd-smoke-tests:debugger-integration-tests:latest-jdk-app",
)

// annotation processor for checking instrumentation advice
include(
  ":dd-java-agent:instrumentation-annotation-processor",
)

// instrumentation:
include(
  ":dd-java-agent:instrumentation:aerospike-4",
  ":dd-java-agent:instrumentation:akka:akka-actor-2.5",
  ":dd-java-agent:instrumentation:akka:akka-http:akka-http-10.0",
  ":dd-java-agent:instrumentation:akka:akka-http:akka-http-10.2-iast",
  ":dd-java-agent:instrumentation:akka:akka-http:akka-http-10.6",
  ":dd-java-agent:instrumentation:apache-httpclient:apache-httpasyncclient-4.0",
  ":dd-java-agent:instrumentation:apache-httpclient:apache-httpclient-4.0",
  ":dd-java-agent:instrumentation:apache-httpclient:apache-httpclient-5.0",
  ":dd-java-agent:instrumentation:apache-httpcore:apache-httpcore-4.0",
  ":dd-java-agent:instrumentation:apache-httpcore:apache-httpcore-5.0",
  ":dd-java-agent:instrumentation:armeria:armeria-grpc-0.84",
  ":dd-java-agent:instrumentation:armeria:armeria-jetty-1.24",
  ":dd-java-agent:instrumentation:avro",
  ":dd-java-agent:instrumentation:aws-java:aws-java-common",
  ":dd-java-agent:instrumentation:aws-java:aws-java-dynamodb-2.0",
  ":dd-java-agent:instrumentation:aws-java:aws-java-eventbridge-2.0",
  ":dd-java-agent:instrumentation:aws-java:aws-java-lambda-handler-1.2",
  ":dd-java-agent:instrumentation:aws-java:aws-java-sdk-1.11",
  ":dd-java-agent:instrumentation:aws-java:aws-java-sdk-2.2",
  ":dd-java-agent:instrumentation:aws-java:aws-java-sfn-2.0",
  ":dd-java-agent:instrumentation:aws-java:aws-java-sns-1.0",
  ":dd-java-agent:instrumentation:aws-java:aws-java-sns-2.0",
  ":dd-java-agent:instrumentation:aws-java:aws-java-sqs-1.0",
  ":dd-java-agent:instrumentation:aws-java:aws-java-sqs-2.0",
  ":dd-java-agent:instrumentation:aws-java:aws-java-s3-2.0",
  ":dd-java-agent:instrumentation:axis-2",
  ":dd-java-agent:instrumentation:axis-1",
  ":dd-java-agent:instrumentation:axway-api",
  ":dd-java-agent:instrumentation:azure-functions",
  ":dd-java-agent:instrumentation:caffeine",
  ":dd-java-agent:instrumentation:cdi-1.2",
  ":dd-java-agent:instrumentation:classloading",
  ":dd-java-agent:instrumentation:classloading:jboss-testing",
  ":dd-java-agent:instrumentation:classloading:jsr14-testing",
  ":dd-java-agent:instrumentation:classloading:osgi-testing",
  ":dd-java-agent:instrumentation:classloading:tomcat-testing",
  ":dd-java-agent:instrumentation:commons-codec-1",
  ":dd-java-agent:instrumentation:commons-fileupload",
  ":dd-java-agent:instrumentation:commons-httpclient-2",
  ":dd-java-agent:instrumentation:commons-lang-2",
  ":dd-java-agent:instrumentation:commons-lang-3",
  ":dd-java-agent:instrumentation:commons-text",
  ":dd-java-agent:instrumentation:couchbase:couchbase-2.0",
  ":dd-java-agent:instrumentation:couchbase:couchbase-2.6",
  ":dd-java-agent:instrumentation:couchbase:couchbase-3.1",
  ":dd-java-agent:instrumentation:couchbase:couchbase-3.2",
  ":dd-java-agent:instrumentation:cucumber",
  ":dd-java-agent:instrumentation:cxf-2.1",
  ":dd-java-agent:instrumentation:datanucleus-4",
  ":dd-java-agent:instrumentation:datastax-cassandra:datastax-cassandra-3.0",
  ":dd-java-agent:instrumentation:datastax-cassandra:datastax-cassandra-3.8",
  ":dd-java-agent:instrumentation:datastax-cassandra:datastax-cassandra-4.0",
  ":dd-java-agent:instrumentation:dropwizard",
  ":dd-java-agent:instrumentation:dropwizard:dropwizard-views",
  ":dd-java-agent:instrumentation:elasticsearch",
  ":dd-java-agent:instrumentation:elasticsearch:rest-5",
  ":dd-java-agent:instrumentation:elasticsearch:rest-6.4",
  ":dd-java-agent:instrumentation:elasticsearch:rest-7",
  ":dd-java-agent:instrumentation:elasticsearch:transport",
  ":dd-java-agent:instrumentation:elasticsearch:transport-2",
  ":dd-java-agent:instrumentation:elasticsearch:transport-5",
  ":dd-java-agent:instrumentation:elasticsearch:transport-5.3",
  ":dd-java-agent:instrumentation:elasticsearch:transport-6",
  ":dd-java-agent:instrumentation:elasticsearch:transport-7.3",
  ":dd-java-agent:instrumentation:enable-wallclock-profiling",
  ":dd-java-agent:instrumentation:exception-profiling",
  ":dd-java-agent:instrumentation:finatra-2.9",
  ":dd-java-agent:instrumentation:freemarker:freemarker-2.3.9",
  ":dd-java-agent:instrumentation:freemarker:freemarker-2.3.24",
  ":dd-java-agent:instrumentation:glassfish",
  ":dd-java-agent:instrumentation:google-http-client",
  ":dd-java-agent:instrumentation:google-pubsub",
  ":dd-java-agent:instrumentation:graal:native-image",
  ":dd-java-agent:instrumentation:gradle-3.0",
  ":dd-java-agent:instrumentation:gradle-8.3",
  ":dd-java-agent:instrumentation:gradle-testing",
  ":dd-java-agent:instrumentation:graphql-java:graphql-java-14.0",
  ":dd-java-agent:instrumentation:graphql-java:graphql-java-20.0",
  ":dd-java-agent:instrumentation:graphql-java:graphql-java-common",
  ":dd-java-agent:instrumentation:grizzly-2",
  ":dd-java-agent:instrumentation:grizzly-client-1.9",
  ":dd-java-agent:instrumentation:grizzly-http-2.3.20",
  ":dd-java-agent:instrumentation:grpc-1.5",
  ":dd-java-agent:instrumentation:gson-1.6",
  ":dd-java-agent:instrumentation:guava-10",
  ":dd-java-agent:instrumentation:hazelcast-3.6",
  ":dd-java-agent:instrumentation:hazelcast-3.9",
  ":dd-java-agent:instrumentation:hazelcast-4.0",
  ":dd-java-agent:instrumentation:hibernate",
  ":dd-java-agent:instrumentation:hibernate:core-3.3",
  ":dd-java-agent:instrumentation:hibernate:core-4.0",
  ":dd-java-agent:instrumentation:hibernate:core-4.3",
  ":dd-java-agent:instrumentation:http-url-connection",
  ":dd-java-agent:instrumentation:hystrix-1.4",
  ":dd-java-agent:instrumentation:iast-instrumenter",
  ":dd-java-agent:instrumentation:ignite-2.0",
  ":dd-java-agent:instrumentation:jackson-core",
  ":dd-java-agent:instrumentation:jackson-core:jackson-core-1",
  ":dd-java-agent:instrumentation:jackson-core:jackson-core-2",
  ":dd-java-agent:instrumentation:jackson-core:jackson-core-2.6",
  ":dd-java-agent:instrumentation:jackson-core:jackson-core-2.8",
  ":dd-java-agent:instrumentation:jackson-core:jackson-core-2.12",
  ":dd-java-agent:instrumentation:jackson-core:jackson-core-2.16",
  ":dd-java-agent:instrumentation:jacoco",
  ":dd-java-agent:instrumentation:jakarta-jms",
  ":dd-java-agent:instrumentation:jakarta-mail",
  ":dd-java-agent:instrumentation:jakarta-rs-annotations-3",
  ":dd-java-agent:instrumentation:jakarta-ws-annotations",
  ":dd-java-agent:instrumentation:java-concurrent",
  ":dd-java-agent:instrumentation:java-concurrent:java-completablefuture",
  ":dd-java-agent:instrumentation:java-concurrent:java-concurrent-21",
  ":dd-java-agent:instrumentation:java-concurrent:lambda-testing",
  ":dd-java-agent:instrumentation:java-directbytebuffer",
  ":dd-java-agent:instrumentation:java-http-client",
  ":dd-java-agent:instrumentation:java-io",
  ":dd-java-agent:instrumentation:java-lang",
  ":dd-java-agent:instrumentation:java-lang:java-lang-9",
  ":dd-java-agent:instrumentation:java-lang:java-lang-11",
  ":dd-java-agent:instrumentation:java-lang:java-lang-15",
  ":dd-java-agent:instrumentation:java-lang:java-lang-17",
  ":dd-java-agent:instrumentation:java-net",
  ":dd-java-agent:instrumentation:java-security",
  ":dd-java-agent:instrumentation:java-util",
  ":dd-java-agent:instrumentation:javax-naming",
  ":dd-java-agent:instrumentation:javax-xml",
  ":dd-java-agent:instrumentation:javax-mail",
  ":dd-java-agent:instrumentation:jax-rs-annotations-1",
  ":dd-java-agent:instrumentation:jax-rs-annotations-2",
  ":dd-java-agent:instrumentation:jax-rs-annotations-2:filter-jersey",
  ":dd-java-agent:instrumentation:jax-rs-annotations-2:filter-resteasy-3.0",
  ":dd-java-agent:instrumentation:jax-rs-annotations-2:filter-resteasy-3.1",
  ":dd-java-agent:instrumentation:jax-rs-client-1.1",
  ":dd-java-agent:instrumentation:jax-rs-client-2.0",
  ":dd-java-agent:instrumentation:jax-rs-client-2.0:connection-error-handling-jersey",
  ":dd-java-agent:instrumentation:jax-rs-client-2.0:connection-error-handling-resteasy",
  ":dd-java-agent:instrumentation:jax-ws-annotations-1",
  ":dd-java-agent:instrumentation:jax-ws-annotations-2",
  ":dd-java-agent:instrumentation:jboss-logmanager",
  ":dd-java-agent:instrumentation:jboss-modules",
  ":dd-java-agent:instrumentation:jdbc",
  ":dd-java-agent:instrumentation:jdbc:scalikejdbc",
  ":dd-java-agent:instrumentation:jedis-1.4",
  ":dd-java-agent:instrumentation:jedis-3.0",
  ":dd-java-agent:instrumentation:jedis-4.0",
  ":dd-java-agent:instrumentation:jersey",
  ":dd-java-agent:instrumentation:jersey-2-appsec",
  ":dd-java-agent:instrumentation:jersey-3-appsec",
  ":dd-java-agent:instrumentation:jetty-7.0",
  ":dd-java-agent:instrumentation:jetty-7.6",
  ":dd-java-agent:instrumentation:jetty-9",
  ":dd-java-agent:instrumentation:jetty-11",
  ":dd-java-agent:instrumentation:jetty-12",
  ":dd-java-agent:instrumentation:jetty-appsec-7",
  ":dd-java-agent:instrumentation:jetty-appsec-8.1.3",
  ":dd-java-agent:instrumentation:jetty-appsec-9.2",
  ":dd-java-agent:instrumentation:jetty-appsec-9.3",
  ":dd-java-agent:instrumentation:jetty-client:jetty-client-common",
  ":dd-java-agent:instrumentation:jetty-client:jetty-client-9.1",
  ":dd-java-agent:instrumentation:jetty-client:jetty-client-10.0",
  ":dd-java-agent:instrumentation:jetty-client:jetty-client-12.0",
  ":dd-java-agent:instrumentation:jetty-common",
  ":dd-java-agent:instrumentation:jetty-util",
  ":dd-java-agent:instrumentation:jms",
  ":dd-java-agent:instrumentation:jose-jwt",
  ":dd-java-agent:instrumentation:org-json",
  ":dd-java-agent:instrumentation:jsp-2.3",
  ":dd-java-agent:instrumentation:junit-4.10",
  ":dd-java-agent:instrumentation:junit-4.10:cucumber-junit-4",
  ":dd-java-agent:instrumentation:junit-4.10:junit-4.13",
  ":dd-java-agent:instrumentation:junit-4.10:munit-junit-4",
  ":dd-java-agent:instrumentation:junit-5.3",
  ":dd-java-agent:instrumentation:junit-5.3:junit-5.8",
  ":dd-java-agent:instrumentation:junit-5.3:cucumber-junit-5",
  ":dd-java-agent:instrumentation:junit-5.3:spock-junit-5",
  ":dd-java-agent:instrumentation:kafka-clients-0.11",
  ":dd-java-agent:instrumentation:kafka-clients-3.8",
  ":dd-java-agent:instrumentation:kafka-common",
  ":dd-java-agent:instrumentation:kafka-connect-0.11",
  ":dd-java-agent:instrumentation:kafka-streams-0.11",
  ":dd-java-agent:instrumentation:kafka-streams-1.0",
  ":dd-java-agent:instrumentation:karate",
  ":dd-java-agent:instrumentation:kotlin-coroutines",
  ":dd-java-agent:instrumentation:lettuce-4",
  ":dd-java-agent:instrumentation:lettuce-5",
  ":dd-java-agent:instrumentation:liberty-20",
  ":dd-java-agent:instrumentation:liberty-23",
  ":dd-java-agent:instrumentation:log4j-2.7",
  ":dd-java-agent:instrumentation:log4j1",
  ":dd-java-agent:instrumentation:log4j2",
  ":dd-java-agent:instrumentation:log4j2:logs-intake",
  ":dd-java-agent:instrumentation:logback-1",
  ":dd-java-agent:instrumentation:maven-3.2.1",
  ":dd-java-agent:instrumentation:maven-surefire",
  ":dd-java-agent:instrumentation:micronaut",
  ":dd-java-agent:instrumentation:micronaut:http-server-netty-2.0",
  ":dd-java-agent:instrumentation:micronaut:http-server-netty-3.0",
  ":dd-java-agent:instrumentation:micronaut:http-server-netty-4.0",
  ":dd-java-agent:instrumentation:mongo",
  ":dd-java-agent:instrumentation:mongo:common",
  ":dd-java-agent:instrumentation:mongo:bson-document",
  ":dd-java-agent:instrumentation:mongo:driver-3.1",
  ":dd-java-agent:instrumentation:mongo:driver-3.4",
  ":dd-java-agent:instrumentation:mongo:driver-3.1-core-test",
  ":dd-java-agent:instrumentation:mongo:driver-3.7-core-test",
  ":dd-java-agent:instrumentation:mongo:driver-4.0",
  ":dd-java-agent:instrumentation:mongo:driver-3.3-async-test",
  ":dd-java-agent:instrumentation:mongo:driver-3.10-sync-test",
  ":dd-java-agent:instrumentation:mule-4",
  ":dd-java-agent:instrumentation:netty-3.8",
  ":dd-java-agent:instrumentation:netty-4.0",
  ":dd-java-agent:instrumentation:netty-4.1-shared",
  ":dd-java-agent:instrumentation:netty-4.1",
  ":dd-java-agent:instrumentation:netty-buffer-4",
  ":dd-java-agent:instrumentation:netty-concurrent-4",
  ":dd-java-agent:instrumentation:netty-promise-4",
  ":dd-java-agent:instrumentation:okhttp-2",
  ":dd-java-agent:instrumentation:okhttp-3",
  ":dd-java-agent:instrumentation:ognl-appsec",
  ":dd-java-agent:instrumentation:opensearch",
  ":dd-java-agent:instrumentation:opensearch:rest",
  ":dd-java-agent:instrumentation:opensearch:transport",
  ":dd-java-agent:instrumentation:opentelemetry:opentelemetry-0.3",
  ":dd-java-agent:instrumentation:opentelemetry:opentelemetry-1.4",
  ":dd-java-agent:instrumentation:opentelemetry:opentelemetry-annotations-1.20",
  ":dd-java-agent:instrumentation:opentelemetry:opentelemetry-annotations-1.26",
  ":dd-java-agent:instrumentation:opentracing",
  ":dd-java-agent:instrumentation:opentracing:api-0.31",
  ":dd-java-agent:instrumentation:opentracing:api-0.32",
  ":dd-java-agent:instrumentation:osgi-4.3",
  ":dd-java-agent:instrumentation:owasp-esapi-2",
  ":dd-java-agent:instrumentation:pekko-concurrent",
  ":dd-java-agent:instrumentation:pekko-http-1.0",
  ":dd-java-agent:instrumentation:play-2.3",
  ":dd-java-agent:instrumentation:play-2.4",
  ":dd-java-agent:instrumentation:play-2.6",
  ":dd-java-agent:instrumentation:play-ws",
  ":dd-java-agent:instrumentation:play-ws-1",
  ":dd-java-agent:instrumentation:play-ws-2",
  ":dd-java-agent:instrumentation:play-ws-2.1",
  ":dd-java-agent:instrumentation:protobuf",
  ":dd-java-agent:instrumentation:quartz-2",
  ":dd-java-agent:instrumentation:rocketmq",
  ":dd-java-agent:instrumentation:rocketmq-5.0",
  ":dd-java-agent:instrumentation:dubbo-apache-2.7",
  ":dd-java-agent:instrumentation:dubbo-apache:dubbo-apache-3.2",
  ":dd-java-agent:instrumentation:dubbo-alibaba",
  ":dd-java-agent:instrumentation:thrift",
  ":dd-java-agent:instrumentation:ons-client",
  ":dd-java-agent:instrumentation:pulsar",
  ":dd-java-agent:instrumentation:taobao-hsf",
  ":dd-java-agent:instrumentation:xxl-job-2.3",
  ":dd-java-agent:instrumentation:rhino",
  ":dd-java-agent:instrumentation:rabbitmq-amqp-2.7",
  ":dd-java-agent:instrumentation:ratpack-1.5",
  ":dd-java-agent:instrumentation:reactive-streams",
  ":dd-java-agent:instrumentation:reactor-core-3.1",
  ":dd-java-agent:instrumentation:reactor-netty-1",
  ":dd-java-agent:instrumentation:rediscala-1.8.0",
  ":dd-java-agent:instrumentation:renaissance",
  ":dd-java-agent:instrumentation:resteasy-appsec",
  ":dd-java-agent:instrumentation:restlet-2.2",
  ":dd-java-agent:instrumentation:rmi",
  ":dd-java-agent:instrumentation:rxjava-1",
  ":dd-java-agent:instrumentation:rxjava-2",
  ":dd-java-agent:instrumentation:scala",
  ":dd-java-agent:instrumentation:scala-concurrent",
  ":dd-java-agent:instrumentation:scala-promise",
  ":dd-java-agent:instrumentation:scala-promise:scala-promise-2.10",
  ":dd-java-agent:instrumentation:scala-promise:scala-promise-2.13",
  ":dd-java-agent:instrumentation:scalatest",
  ":dd-java-agent:instrumentation:selenium",
  ":dd-java-agent:instrumentation:servicetalk",
  ":dd-java-agent:instrumentation:servicetalk:servicetalk-0.42.0",
  ":dd-java-agent:instrumentation:servicetalk:servicetalk-0.42.56",
  ":dd-java-agent:instrumentation:servlet",
  ":dd-java-agent:instrumentation:servlet-common",
  ":dd-java-agent:instrumentation:servlet:request-2",
  ":dd-java-agent:instrumentation:servlet:request-3",
  ":dd-java-agent:instrumentation:servlet:request-5",
  ":dd-java-agent:instrumentation:shutdown",
  ":dd-java-agent:instrumentation:slick",
  ":dd-java-agent:instrumentation:snakeyaml",
  ":dd-java-agent:instrumentation:span-origin",
  ":dd-java-agent:instrumentation:spark:spark_2.12",
  ":dd-java-agent:instrumentation:spark:spark_2.13",
  ":dd-java-agent:instrumentation:spark-executor",
  ":dd-java-agent:instrumentation:sparkjava-2.3",
  ":dd-java-agent:instrumentation:spray-1.3",
  ":dd-java-agent:instrumentation:spring-beans",
  ":dd-java-agent:instrumentation:spring-boot",
  ":dd-java-agent:instrumentation:spring-cloud-zuul-2",
  ":dd-java-agent:instrumentation:spring-core",
  ":dd-java-agent:instrumentation:spring-data-1.8",
  ":dd-java-agent:instrumentation:spring-jms-3.1",
  ":dd-java-agent:instrumentation:spring-messaging-4",
  ":dd-java-agent:instrumentation:spring-rabbit",
  ":dd-java-agent:instrumentation:spring-scheduling-3.1",
  ":dd-java-agent:instrumentation:spring-security-5",
  ":dd-java-agent:instrumentation:spring-security-6",
  ":dd-java-agent:instrumentation:spring-webflux-5",
  ":dd-java-agent:instrumentation:spring-webflux-6",
  ":dd-java-agent:instrumentation:spring-webmvc-3.1",
  ":dd-java-agent:instrumentation:spring-webmvc-5.3",
  ":dd-java-agent:instrumentation:spring-webmvc-6.0",
  ":dd-java-agent:instrumentation:spring-ws-2",
  ":dd-java-agent:instrumentation:spymemcached-2.10",
  ":dd-java-agent:instrumentation:sslsocket",
  ":dd-java-agent:instrumentation:synapse-3",
  ":dd-java-agent:instrumentation:testng",
  ":dd-java-agent:instrumentation:testng:testng-6",
  ":dd-java-agent:instrumentation:testng:testng-7",
  ":dd-java-agent:instrumentation:thymeleaf",
  ":dd-java-agent:instrumentation:tinylog-2",
  ":dd-java-agent:instrumentation:tibco-businessworks",
  ":dd-java-agent:instrumentation:tibco-businessworks:tibcobw-stubs",
  ":dd-java-agent:instrumentation:tibco-businessworks:tibcobw-5",
  ":dd-java-agent:instrumentation:tibco-businessworks:tibcobw-6",
  ":dd-java-agent:instrumentation:tomcat-5.5",
  ":dd-java-agent:instrumentation:tomcat-5.5-common",
  ":dd-java-agent:instrumentation:tomcat-appsec-5.5",
  ":dd-java-agent:instrumentation:tomcat-appsec-6",
  ":dd-java-agent:instrumentation:tomcat-appsec-7",
  ":dd-java-agent:instrumentation:tomcat-classloading-9",
  ":dd-java-agent:instrumentation:trace-annotation",
  ":dd-java-agent:instrumentation:twilio",
  ":dd-java-agent:instrumentation:unbescape",
  ":dd-java-agent:instrumentation:undertow",
  ":dd-java-agent:instrumentation:undertow:undertow-2.0",
  ":dd-java-agent:instrumentation:undertow:undertow-2.2",
  ":dd-java-agent:instrumentation:valkey-java",
  ":dd-java-agent:instrumentation:velocity",
  ":dd-java-agent:instrumentation:vertx-mysql-client-3.9",
  ":dd-java-agent:instrumentation:vertx-mysql-client-4.0",
  ":dd-java-agent:instrumentation:vertx-mysql-client-4.4.2",
  ":dd-java-agent:instrumentation:vertx-pg-client-4.0",
  ":dd-java-agent:instrumentation:vertx-pg-client-4.4.2",
  ":dd-java-agent:instrumentation:vertx-redis-client-3.9",
  ":dd-java-agent:instrumentation:vertx-redis-client-3.9:stubs",
  ":dd-java-agent:instrumentation:vertx-rx-3.5",
  ":dd-java-agent:instrumentation:vertx-sql-client-3.9",
  ":dd-java-agent:instrumentation:vertx-web-3.4",
  ":dd-java-agent:instrumentation:vertx-web-3.5",
  ":dd-java-agent:instrumentation:vertx-web-3.9",
  ":dd-java-agent:instrumentation:vertx-web-4.0",
  ":dd-java-agent:instrumentation:vertx-web-5.0",
  ":dd-java-agent:instrumentation:redisson",
  ":dd-java-agent:instrumentation:redisson:redisson-2.0.0",
  ":dd-java-agent:instrumentation:redisson:redisson-2.3.0",
  ":dd-java-agent:instrumentation:redisson:redisson-3.10.3",
  ":dd-java-agent:instrumentation:weaver",
  ":dd-java-agent:instrumentation:websocket:jakarta-websocket-2.0",
  ":dd-java-agent:instrumentation:websocket:javax-websocket-1.0",
  ":dd-java-agent:instrumentation:websocket:jetty-websocket",
  ":dd-java-agent:instrumentation:websocket:jetty-websocket:jetty-websocket-10",
  ":dd-java-agent:instrumentation:websocket:jetty-websocket:jetty-websocket-11",
  ":dd-java-agent:instrumentation:websocket:jetty-websocket:jetty-websocket-12",
  ":dd-java-agent:instrumentation:websphere-jmx",
  ":dd-java-agent:instrumentation:wildfly-9",
  ":dd-java-agent:instrumentation:zio:zio-2.0",
)

// benchmark
include(
  ":dd-java-agent:benchmark",
  ":dd-java-agent:benchmark-integration",
  ":dd-java-agent:benchmark-integration:jetty-perftest",
  ":dd-java-agent:benchmark-integration:play-perftest",
)
