package com.datadog.debugger.symbol;

import java.util.List;

public class WireFilter implements ScopeFilter {
  @Override
  public boolean filterOut(Scope scope) {
    // Filter out classes generated by Square Wire: https://square.github.io/wire/
    if (scope == null) {
      return false;
    }
    LanguageSpecifics languageSpecifics = scope.getLanguageSpecifics();
    if (languageSpecifics == null) {
      return false;
    }
    List<String> interfaces = languageSpecifics.getInterfaces();
    if (interfaces != null) {
      if (interfaces.contains("com.squareup.wire.Message")) {
        // Pass-through for Message since it contains data
        return false;
      }
      if (interfaces.stream().anyMatch(it -> it.startsWith("com.squareup.wire"))) {
        return true;
      }
    }
    String superClass = languageSpecifics.getSuperClass();
    if (superClass != null) {
      if (superClass.startsWith("com.squareup.wire")) {
        return true;
      }
    }
    // Probably no protobuf, pass
    return false;
  }
}
