plugins {
  id 'dd-trace-java.module.instrumentation'
  id 'dd-trace-java.jmh-conventions'
}

configurations.configureEach {
  // shut up about broken xml-api pom relocation
  resolutionStrategy {
    force 'xml-apis:xml-apis:1.4.01'
  }
}

def tomcatVersion = '5.5.12' // earliest 5.5.x available in maven central (with all needed dependencies).
dependencies {
  compileOnly group: 'tomcat', name: 'catalina', version: tomcatVersion
  compileOnly group: 'tomcat', name: 'tomcat-coyote', version: tomcatVersion
  compileOnly group: 'tomcat', name: 'tomcat-util', version: tomcatVersion

  // Version that corresponds with Tomcat 5.5
  // https://tomcat.apache.org/whichversion.html
  compileOnly group: 'javax.servlet', name: 'servlet-api', version: '2.4'
}

jmh {
  jmhVersion = libs.versions.jmh.get()
  includeTests = false
}

tasks.named('compileJmhJava', JavaCompile) {
  configureCompiler(it, JavaVersion.VERSION_1_8)
}

dependencies {
  jmh "org.apache.tomcat.embed:tomcat-embed-core:${findProperty('jmhTomcatVersion') ?: '11.0.26'}"
}
