#!/usr/bin/env python3

import json
import os
import sys
from io import StringIO

import numpy as np

from python_utils import compute_confidence_interval, import_benchmark_values, round_value

NO_AGENT_VARIANT = os.getenv("NO_AGENT_VARIANT")
CI_INTERVAL = 0.99
UOM = "µs"
CANDIDATE = os.getenv("CANDIDATE_VERSION")
BASELINE = os.getenv("BASELINE_VERSION")

input_folder = sys.argv[1]


def _get_variant_from_scenario(scenario: str) -> str:
    return scenario.split(":")[2]


def _parse_benchmarks(folder: str, build: str) -> dict[str, list[float]]:
    with open(f"{folder}/benchmark-{build}.json", "r", encoding="utf-8") as reader:
        benchmark_json = json.loads(reader.read())

    return {
        _get_variant_from_scenario(b["parameters"]["scenario"]): import_benchmark_values(
            b, "http_req_duration", UOM
        )
        for b in benchmark_json["benchmarks"]
    }


def _sort_variants(item: str) -> str:
    if item == NO_AGENT_VARIANT:
        return ""
    return item


def _build_application_results(folder: str) -> str:
    application = os.path.basename(folder)
    chart = StringIO()
    tables = {
        "baseline": StringIO(),
        "candidate": StringIO(),
    }
    values = {
        "baseline": dict(),
        "candidate": dict(),
    }

    values["candidate"] = _parse_benchmarks(os.path.join(application_folder, "_merged_k6_results"), "candidate")
    values["baseline"] = _parse_benchmarks(os.path.join(application_folder, "_merged_k6_results"), "baseline")

    no_agent_means = {
        "baseline": float(np.mean(values["baseline"][NO_AGENT_VARIANT])),
        "candidate": float(np.mean(values["candidate"][NO_AGENT_VARIANT])),
    }
    variants = sorted(values["candidate"].keys(), key=_sort_variants)
    chart.write(
        f"""
```mermaid
gantt
    title {application} - request duration [CI {CI_INTERVAL}] : candidate={CANDIDATE}, baseline={BASELINE}
    dateFormat X
    axisFormat %s
"""
    )

    for build in ("baseline", "candidate"):
        table = tables[build]
        table.write(f"\n|Variant|Request duration [CI {CI_INTERVAL}]|Δ {NO_AGENT_VARIANT}|\n")
        table.write("|---|---|---|\n")
        build_values = values[build]
        no_agent_mean = no_agent_means[build]
        chart.write(f"section {build}\n")
        for variant in variants:
            variant_values = build_values[variant]
            mean = float(np.mean(variant_values))
            lower, upper = compute_confidence_interval(variant_values, CI_INTERVAL)
            overhead = mean - no_agent_mean
            overhead_pct = overhead * 100 / no_agent_mean
            chart.write(f"{variant} ({round_value(mean, UOM)}) : {round(lower)}, {round(upper)}\n")
            chart.write(f".   : milestone, {round(mean)},\n")
            table.write(
                f"|{variant}|{round_value(mean, UOM)} [{round_value(lower, UOM)}, {round_value(upper, UOM)}]"
                f"|{'-' if variant == NO_AGENT_VARIANT else f'{round_value(overhead, UOM)} ({round(overhead_pct, 1)}%)'}|\n"
            )

    chart.write("```\n")

    result = StringIO()
    result.write(f"\n\n<details><summary>Request duration reports for {application}</summary>\n")
    result.write(chart.getvalue())
    for build, table in tables.items():
        result.write(f"\n* **{build}** results\n")
        result.write(table.getvalue())
    result.write("\n</details>\n")
    return result.getvalue()


for application_folder in [f.path for f in os.scandir(input_folder) if f.is_dir()]:
    print(_build_application_results(application_folder))
