plugins {
  id 'dd-trace-java.module.instrumentation'
  id 'dd-trace-java.call-site-instrumentation'
}

testJvmConstraints {
  minJavaVersion = JavaVersion.VERSION_15
}

muzzle {
  pass {
    coreJdk()
  }
}

csi {
  javaVersion = JavaLanguageVersion.of(17)
}

addTestSuiteForDir('latestDepTest', 'test')

dependencies {
  testImplementation(libs.javaparser)
  testRuntimeOnly project(':dd-java-agent:instrumentation:datadog:asm:iast-instrumenter')
}

tasks.withType(AbstractCompile).configureEach {
  switch (it.name) {
    case 'compileCsiJava':
      break
    default:
      configureCompiler(it, JavaVersion.VERSION_15)
  }
}
