package datadog.gradle.plugin.tags

/**
 * Emits the generated `KnownTags.java` from a [TagRegistry]. Public API first — per-tag
 * `<X>_NAME` (string) + `<X>_ID` (encoded long, literal) couplets with a trailing `// makeTagId(...)`
 * derivation comment — then the package-private `<X>_SERIAL_NUM` constants, the
 * `StringIndex.EmbeddingSupport` keyOf table, the `serialNum` switch `nameOf`, and resolver
 * registration.
 */
object KnownTagsEmitter {

  fun emit(reg: TagRegistry, pkg: String, className: String): String {
    // Sanitize tag names into unique Java constant identifiers.
    val used = HashSet<String>()
    val cname = HashMap<String, String>()
    fun mk(name: String): String {
      var c = name.uppercase().replace(Regex("[^A-Za-z0-9]"), "_").replace(Regex("_+"), "_").trim('_')
      if (c.isEmpty() || c[0].isDigit()) c = "T_$c"
      var u = c
      var n = 2
      while (u in used) {
        u = "${c}_$n"; n++
      }
      used.add(u)
      cname[name] = u
      return u
    }
    reg.reserved.forEach { mk(it.name) }
    reg.stored.forEach { mk(it.name) }

    // Constant names. Collapse a duplicated trailing token so e.g. "resource.name" yields NAME
    // (not NAME_NAME) and "_dd.parent_id" yields ID (not ID_ID); the non-duplicating pairs
    // (ID + _NAME -> ID_NAME, NAME + _ID -> NAME_ID) are kept as-is.
    fun withSuffix(base: String, suffix: String) = if (base.endsWith(suffix)) base else "$base$suffix"
    fun nameC(name: String) = withSuffix(cname[name]!!, "_NAME")
    fun idC(name: String) = withSuffix(cname[name]!!, "_ID")
    fun serialC(name: String) = withSuffix(cname[name]!!, "_SERIAL_NUM")

    val order = reg.reserved.map { it.name } + reg.stored.map { it.name } // stable emit order
    val b = StringBuilder()
    b.appendLine("package $pkg;")
    b.appendLine()
    b.appendLine("import datadog.trace.util.StringIndex;")
    b.appendLine()
    b.appendLine("// GENERATED by the tag-registry code generator (dd-trace-java.tag-registry-generator).")
    b.appendLine("// DO NOT EDIT. Source: tag-conventions.yaml + tag-conventions.java.yaml.")
    b.appendLine("public final class $className {")
    b.appendLine("  static final int SLOT_COUNT = ${reg.slotCount};")
    b.appendLine()

    // Public API first (name + encoded id couplets), so readers see the useful parts up top; the
    // serial ids and keyOf/resolver machinery follow below. Derivation is in the trailing comment.
    b.appendLine("  // ---- reserved (routed to span fields or directives; not stored) ----")
    for (v in reg.reserved) {
      b.appendLine("  public static final String ${nameC(v.name)} = \"${v.name}\";")
      b.appendLine("  public static final long ${idC(v.name)} = ${hex(v.id)};")
      b.appendLine("  // makeTagId(serial=${v.serial}, group=0, field=NO_SLOT) + intercepted  [${v.kind}${v.field?.let { " -> $it" } ?: ""}]")
      b.appendLine()
    }

    b.appendLine("  // ---- stored (dense field-decl, or bucketed when field=NO_SLOT) ----")
    for (t in reg.stored) {
      val field = if (t.slotted) t.fieldDecl.toString() else "NO_SLOT"
      b.appendLine("  public static final String ${nameC(t.name)} = \"${t.name}\";")
      b.appendLine("  public static final long ${idC(t.name)} = ${hex(t.id)};")
      b.appendLine("  // makeTagId(serial=${t.serial}, group=${t.groupDecl}, field=$field)${if (t.intercepted) " + intercepted" else ""}  <${t.required}${if (t.traceLevel) ", trace-level" else ""}>")
      b.appendLine()
    }

    // Serial numbers (globalSerial per tag) — package-private, consumed by the resolver switch.
    b.appendLine("  // ---- serial numbers ----")
    for (v in reg.reserved) {
      b.appendLine("  static final int ${serialC(v.name)} = ${v.serial};")
    }
    for (t in reg.stored) {
      b.appendLine("  static final int ${serialC(t.name)} = ${t.serial};")
    }
    b.appendLine()

    // keyOf table (open-addressed, via StringIndex.EmbeddingSupport).
    b.appendLine("  private static final String[] KEYOF_NAMES = {")
    order.forEach { b.appendLine("    ${nameC(it)},") }
    b.appendLine("  };")
    b.appendLine("  private static final long[] KEYOF_VALUES = {")
    order.forEach { b.appendLine("    ${idC(it)},") }
    b.appendLine("  };")
    b.appendLine("  private static final int[] KEYOF_HASHES;")
    b.appendLine("  private static final String[] KEYOF_KEYS;")
    b.appendLine("  private static final long[] KEYOF_IDS;")
    b.appendLine("  static {")
    b.appendLine("    StringIndex.Data data = StringIndex.EmbeddingSupport.create(KEYOF_NAMES);")
    b.appendLine("    long[] ids = new long[data.names.length];")
    b.appendLine("    for (int j = 0; j < KEYOF_NAMES.length; j++) {")
    b.appendLine("      ids[StringIndex.EmbeddingSupport.indexOf(data.hashes, data.names, KEYOF_NAMES[j])] = KEYOF_VALUES[j];")
    b.appendLine("    }")
    b.appendLine("    KEYOF_HASHES = data.hashes;")
    b.appendLine("    KEYOF_KEYS = data.names;")
    b.appendLine("    KEYOF_IDS = ids;")
    b.appendLine("  }")
    b.appendLine()

    // Resolver.
    b.appendLine("  static final KnownTagCodec.Resolver RESOLVER =")
    b.appendLine("      new KnownTagCodec.Resolver() {")
    b.appendLine("        @Override")
    b.appendLine("        public String nameOf(long tagId) {")
    b.appendLine("          switch (KnownTagCodec.serialNum(tagId)) {")
    for (name in order) {
      b.appendLine("            case ${serialC(name)}:")
      b.appendLine("              return ${nameC(name)};")
    }
    b.appendLine("            default:")
    b.appendLine("              return null;")
    b.appendLine("          }")
    b.appendLine("        }")
    b.appendLine()
    b.appendLine("        @Override")
    b.appendLine("        public int slotCount() {")
    b.appendLine("          return SLOT_COUNT;")
    b.appendLine("        }")
    b.appendLine()
    b.appendLine("        @Override")
    b.appendLine("        public long keyOf(String name) {")
    b.appendLine("          int slot = StringIndex.EmbeddingSupport.indexOf(KEYOF_HASHES, KEYOF_KEYS, name);")
    b.appendLine("          return slot < 0 ? 0L : KEYOF_IDS[slot];")
    b.appendLine("        }")
    b.appendLine("      };")
    b.appendLine()
    b.appendLine("  static {")
    b.appendLine("    KnownTagCodec.register(RESOLVER);")
    b.appendLine("  }")
    b.appendLine()
    b.appendLine("  /** Forces resolver registration by triggering <clinit>. Idempotent. */")
    b.appendLine("  public static void init() {}")
    b.appendLine()
    b.appendLine("  private $className() {}")
    b.appendLine("}")
    return b.toString()
  }

  private fun hex(id: Long): String = "0x%016XL".format(id)
}
