[ {
  "content" : {
    "duration" : ${content_duration},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[4, 5]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.adding(int,int)",
      "step.name" : "I add {int} and {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id},
    "resource" : "I add {int} and {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id},
    "start" : ${content_start},
    "trace_id" : ${content_trace_id}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_2},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_2},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[4, 5]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.adding(int,int)",
      "step.name" : "I add {int} and {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_2},
    "resource" : "I add {int} and {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_2},
    "start" : ${content_start_2},
    "trace_id" : ${content_trace_id_2}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_3},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_3},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[4, 5]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.adding(int,int)",
      "step.name" : "I add {int} and {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_3},
    "resource" : "I add {int} and {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_3},
    "start" : ${content_start_3},
    "trace_id" : ${content_trace_id_3}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_4},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_4},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[4, 5]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.adding(int,int)",
      "step.name" : "I add {int} and {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_4},
    "resource" : "I add {int} and {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_4},
    "start" : ${content_start_4},
    "trace_id" : ${content_trace_id_4}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_5},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_5},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[4, 5]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.adding(int,int)",
      "step.name" : "I add {int} and {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_5},
    "resource" : "I add {int} and {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_5},
    "start" : ${content_start_5},
    "trace_id" : ${content_trace_id_5}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_6},
    "error" : 1,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_6},
      "_dd.test.is_user_provided_service" : "true",
      "_dd.tracer_host" : ${content_meta__dd_tracer_host},
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "maven",
      "env" : "integration-test",
      "error.message" : ${content_meta_error_message},
      "error.stack" : ${content_meta_error_stack},
      "error.type" : "org.apache.maven.lifecycle.LifecycleExecutionException",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id_2},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test_session_end",
      "test.code_coverage.enabled" : "true",
      "test.command" : "mvn -B test",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.status" : "fail",
      "test.toolchain" : ${content_meta_test_toolchain},
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count},
      "_dd.profiling.enabled" : 0,
      "_dd.trace_span_attribute_schema" : 0,
      "process_id" : ${content_metrics_process_id}
    },
    "name" : "maven.test_session",
    "resource" : "Maven Smoke Tests Project",
    "service" : "test-maven-service",
    "start" : ${content_start_6},
    "test_session_id" : ${content_test_session_id}
  },
  "type" : "test_session_end",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_7},
    "error" : 1,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_7},
      "_dd.test.is_user_provided_service" : "true",
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "maven",
      "env" : "integration-test",
      "error.message" : ${content_meta_error_message},
      "error.stack" : ${content_meta_error_stack_2},
      "error.type" : "org.apache.maven.lifecycle.LifecycleExecutionException",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id_2},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test_module_end",
      "test.code_coverage.enabled" : "true",
      "test.command" : "mvn -B test",
      "test.execution" : "maven-surefire-plugin:test:default-test",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.module" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
      "test.status" : "fail",
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count_2}
    },
    "name" : "maven.test_module",
    "resource" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
    "service" : "test-maven-service",
    "start" : ${content_start_7},
    "test_module_id" : ${content_test_module_id},
    "test_session_id" : ${content_test_session_id}
  },
  "type" : "test_module_end",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_8},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_8},
      "_dd.test.is_user_provided_service" : "true",
      "env" : "integration-test",
      "execution" : "default-compile",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "plugin" : "maven-compiler-plugin",
      "project" : "Maven Smoke Tests Project",
      "runtime-id" : ${content_meta_runtime_id_2},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version}
    },
    "metrics" : { },
    "name" : "Maven_Smoke_Tests_Project_maven_compiler_plugin_default_compile",
    "parent_id" : ${content_test_session_id},
    "resource" : "Maven_Smoke_Tests_Project_maven_compiler_plugin_default_compile",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_6},
    "start" : ${content_start_8},
    "trace_id" : ${content_test_session_id}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_9},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_9},
      "_dd.test.is_user_provided_service" : "true",
      "env" : "integration-test",
      "execution" : "default-testCompile",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "plugin" : "maven-compiler-plugin",
      "project" : "Maven Smoke Tests Project",
      "runtime-id" : ${content_meta_runtime_id_2},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version}
    },
    "metrics" : { },
    "name" : "Maven_Smoke_Tests_Project_maven_compiler_plugin_default_testCompile",
    "parent_id" : ${content_test_session_id},
    "resource" : "Maven_Smoke_Tests_Project_maven_compiler_plugin_default_testCompile",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_7},
    "start" : ${content_start_9},
    "trace_id" : ${content_test_session_id}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_10},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_10},
      "_dd.test.is_user_provided_service" : "true",
      "env" : "integration-test",
      "execution" : "default-resources",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "plugin" : "maven-resources-plugin",
      "project" : "Maven Smoke Tests Project",
      "runtime-id" : ${content_meta_runtime_id_2},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version}
    },
    "metrics" : { },
    "name" : "Maven_Smoke_Tests_Project_maven_resources_plugin_default_resources",
    "parent_id" : ${content_test_session_id},
    "resource" : "Maven_Smoke_Tests_Project_maven_resources_plugin_default_resources",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_8},
    "start" : ${content_start_10},
    "trace_id" : ${content_test_session_id}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_11},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_11},
      "_dd.test.is_user_provided_service" : "true",
      "env" : "integration-test",
      "execution" : "default-testResources",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "plugin" : "maven-resources-plugin",
      "project" : "Maven Smoke Tests Project",
      "runtime-id" : ${content_meta_runtime_id_2},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version}
    },
    "metrics" : { },
    "name" : "Maven_Smoke_Tests_Project_maven_resources_plugin_default_testResources",
    "parent_id" : ${content_test_session_id},
    "resource" : "Maven_Smoke_Tests_Project_maven_resources_plugin_default_testResources",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_9},
    "start" : ${content_start_11},
    "trace_id" : ${content_test_session_id}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_12},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_12},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.a_calculator_I_just_turned_on()",
      "step.name" : "a calculator I just turned on",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id},
    "resource" : "a calculator I just turned on",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_10},
    "start" : ${content_start_12},
    "trace_id" : ${content_trace_id}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_13},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_13},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.a_calculator_I_just_turned_on()",
      "step.name" : "a calculator I just turned on",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_2},
    "resource" : "a calculator I just turned on",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_11},
    "start" : ${content_start_13},
    "trace_id" : ${content_trace_id_2}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_14},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_14},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.a_calculator_I_just_turned_on()",
      "step.name" : "a calculator I just turned on",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_3},
    "resource" : "a calculator I just turned on",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_12},
    "start" : ${content_start_14},
    "trace_id" : ${content_trace_id_3}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_15},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_15},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.a_calculator_I_just_turned_on()",
      "step.name" : "a calculator I just turned on",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_4},
    "resource" : "a calculator I just turned on",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_13},
    "start" : ${content_start_15},
    "trace_id" : ${content_trace_id_4}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_16},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_16},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.a_calculator_I_just_turned_on()",
      "step.name" : "a calculator I just turned on",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_5},
    "resource" : "a calculator I just turned on",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_14},
    "start" : ${content_start_16},
    "trace_id" : ${content_trace_id_5}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_17},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_17},
      "_dd.test.is_user_provided_service" : "true",
      "_dd.tracer_host" : ${content_meta__dd_tracer_host},
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test_suite_end",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.module" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
      "test.status" : "fail",
      "test.suite" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic",
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count_3},
      "_dd.profiling.enabled" : 0,
      "_dd.trace_span_attribute_schema" : 0,
      "process_id" : ${content_metrics_process_id_2}
    },
    "name" : "cucumber.test_suite",
    "resource" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic",
    "service" : "test-maven-service",
    "start" : ${content_start_17},
    "test_module_id" : ${content_test_module_id},
    "test_session_id" : ${content_test_session_id},
    "test_suite_id" : ${content_test_suite_id}
  },
  "type" : "test_suite_end",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_18},
    "error" : 1,
    "meta" : {
      "_dd.library_capabilities.auto_test_retries" : "1",
      "_dd.library_capabilities.coverage_report_upload" : "1",
      "_dd.library_capabilities.early_flake_detection" : "1",
      "_dd.library_capabilities.failed_test_replay" : "1",
      "_dd.library_capabilities.test_impact_analysis" : "1",
      "_dd.library_capabilities.test_management.attempt_to_fix" : "5",
      "_dd.library_capabilities.test_management.disable" : "1",
      "_dd.library_capabilities.test_management.quarantine" : "1",
      "_dd.p.tid" : ${content_meta__dd_p_tid_18},
      "_dd.test.is_user_provided_service" : "true",
      "_dd.tracer_host" : ${content_meta__dd_tracer_host},
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "cucumber",
      "env" : "integration-test",
      "error.message" : ${content_meta_error_message_2},
      "error.stack" : ${content_meta_error_stack_3},
      "error.type" : "java.lang.AssertionError",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test",
      "test.failure_suppressed" : "true",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.module" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
      "test.name" : "Basic Arithmetic - Addition",
      "test.status" : "fail",
      "test.suite" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic",
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count_4},
      "_dd.profiling.enabled" : 0,
      "_dd.trace_span_attribute_schema" : 0,
      "process_id" : ${content_metrics_process_id_2}
    },
    "name" : "cucumber.test",
    "parent_id" : ${content_parent_id_6},
    "resource" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic.Basic Arithmetic - Addition",
    "service" : "test-maven-service",
    "span_id" : ${content_parent_id},
    "start" : ${content_start_18},
    "test_module_id" : ${content_test_module_id},
    "test_session_id" : ${content_test_session_id},
    "test_suite_id" : ${content_test_suite_id},
    "trace_id" : ${content_trace_id}
  },
  "type" : "test",
  "version" : 2
}, {
  "content" : {
    "duration" : ${content_duration_19},
    "error" : 1,
    "meta" : {
      "_dd.library_capabilities.auto_test_retries" : "1",
      "_dd.library_capabilities.coverage_report_upload" : "1",
      "_dd.library_capabilities.early_flake_detection" : "1",
      "_dd.library_capabilities.failed_test_replay" : "1",
      "_dd.library_capabilities.test_impact_analysis" : "1",
      "_dd.library_capabilities.test_management.attempt_to_fix" : "5",
      "_dd.library_capabilities.test_management.disable" : "1",
      "_dd.library_capabilities.test_management.quarantine" : "1",
      "_dd.p.tid" : ${content_meta__dd_p_tid_19},
      "_dd.test.is_user_provided_service" : "true",
      "_dd.tracer_host" : ${content_meta__dd_tracer_host},
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "cucumber",
      "env" : "integration-test",
      "error.message" : ${content_meta_error_message_2},
      "error.stack" : ${content_meta_error_stack_4},
      "error.type" : "java.lang.AssertionError",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test",
      "test.failure_suppressed" : "true",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.is_retry" : "true",
      "test.module" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
      "test.name" : "Basic Arithmetic - Addition",
      "test.retry_reason" : "auto_test_retry",
      "test.status" : "fail",
      "test.suite" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic",
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count_5},
      "_dd.profiling.enabled" : 0,
      "_dd.trace_span_attribute_schema" : 0,
      "process_id" : ${content_metrics_process_id_2}
    },
    "name" : "cucumber.test",
    "parent_id" : ${content_parent_id_6},
    "resource" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic.Basic Arithmetic - Addition",
    "service" : "test-maven-service",
    "span_id" : ${content_parent_id_2},
    "start" : ${content_start_19},
    "test_module_id" : ${content_test_module_id},
    "test_session_id" : ${content_test_session_id},
    "test_suite_id" : ${content_test_suite_id},
    "trace_id" : ${content_trace_id_2}
  },
  "type" : "test",
  "version" : 2
}, {
  "content" : {
    "duration" : ${content_duration_20},
    "error" : 1,
    "meta" : {
      "_dd.library_capabilities.auto_test_retries" : "1",
      "_dd.library_capabilities.coverage_report_upload" : "1",
      "_dd.library_capabilities.early_flake_detection" : "1",
      "_dd.library_capabilities.failed_test_replay" : "1",
      "_dd.library_capabilities.test_impact_analysis" : "1",
      "_dd.library_capabilities.test_management.attempt_to_fix" : "5",
      "_dd.library_capabilities.test_management.disable" : "1",
      "_dd.library_capabilities.test_management.quarantine" : "1",
      "_dd.p.tid" : ${content_meta__dd_p_tid_20},
      "_dd.test.is_user_provided_service" : "true",
      "_dd.tracer_host" : ${content_meta__dd_tracer_host},
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "cucumber",
      "env" : "integration-test",
      "error.message" : ${content_meta_error_message_2},
      "error.stack" : ${content_meta_error_stack_5},
      "error.type" : "java.lang.AssertionError",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test",
      "test.failure_suppressed" : "true",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.is_retry" : "true",
      "test.module" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
      "test.name" : "Basic Arithmetic - Addition",
      "test.retry_reason" : "auto_test_retry",
      "test.status" : "fail",
      "test.suite" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic",
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count_6},
      "_dd.profiling.enabled" : 0,
      "_dd.trace_span_attribute_schema" : 0,
      "process_id" : ${content_metrics_process_id_2}
    },
    "name" : "cucumber.test",
    "parent_id" : ${content_parent_id_6},
    "resource" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic.Basic Arithmetic - Addition",
    "service" : "test-maven-service",
    "span_id" : ${content_parent_id_3},
    "start" : ${content_start_20},
    "test_module_id" : ${content_test_module_id},
    "test_session_id" : ${content_test_session_id},
    "test_suite_id" : ${content_test_suite_id},
    "trace_id" : ${content_trace_id_3}
  },
  "type" : "test",
  "version" : 2
}, {
  "content" : {
    "duration" : ${content_duration_21},
    "error" : 1,
    "meta" : {
      "_dd.library_capabilities.auto_test_retries" : "1",
      "_dd.library_capabilities.coverage_report_upload" : "1",
      "_dd.library_capabilities.early_flake_detection" : "1",
      "_dd.library_capabilities.failed_test_replay" : "1",
      "_dd.library_capabilities.test_impact_analysis" : "1",
      "_dd.library_capabilities.test_management.attempt_to_fix" : "5",
      "_dd.library_capabilities.test_management.disable" : "1",
      "_dd.library_capabilities.test_management.quarantine" : "1",
      "_dd.p.tid" : ${content_meta__dd_p_tid_21},
      "_dd.test.is_user_provided_service" : "true",
      "_dd.tracer_host" : ${content_meta__dd_tracer_host},
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "cucumber",
      "env" : "integration-test",
      "error.message" : ${content_meta_error_message_2},
      "error.stack" : ${content_meta_error_stack_6},
      "error.type" : "java.lang.AssertionError",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test",
      "test.failure_suppressed" : "true",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.is_retry" : "true",
      "test.module" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
      "test.name" : "Basic Arithmetic - Addition",
      "test.retry_reason" : "auto_test_retry",
      "test.status" : "fail",
      "test.suite" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic",
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count_7},
      "_dd.profiling.enabled" : 0,
      "_dd.trace_span_attribute_schema" : 0,
      "process_id" : ${content_metrics_process_id_2}
    },
    "name" : "cucumber.test",
    "parent_id" : ${content_parent_id_6},
    "resource" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic.Basic Arithmetic - Addition",
    "service" : "test-maven-service",
    "span_id" : ${content_parent_id_4},
    "start" : ${content_start_21},
    "test_module_id" : ${content_test_module_id},
    "test_session_id" : ${content_test_session_id},
    "test_suite_id" : ${content_test_suite_id},
    "trace_id" : ${content_trace_id_4}
  },
  "type" : "test",
  "version" : 2
}, {
  "content" : {
    "duration" : ${content_duration_22},
    "error" : 1,
    "meta" : {
      "_dd.library_capabilities.auto_test_retries" : "1",
      "_dd.library_capabilities.coverage_report_upload" : "1",
      "_dd.library_capabilities.early_flake_detection" : "1",
      "_dd.library_capabilities.failed_test_replay" : "1",
      "_dd.library_capabilities.test_impact_analysis" : "1",
      "_dd.library_capabilities.test_management.attempt_to_fix" : "5",
      "_dd.library_capabilities.test_management.disable" : "1",
      "_dd.library_capabilities.test_management.quarantine" : "1",
      "_dd.p.tid" : ${content_meta__dd_p_tid_22},
      "_dd.test.is_user_provided_service" : "true",
      "_dd.tracer_host" : ${content_meta__dd_tracer_host},
      "ci.workspace_path" : ${content_meta_ci_workspace_path},
      "component" : "cucumber",
      "env" : "integration-test",
      "error.message" : ${content_meta_error_message_2},
      "error.stack" : ${content_meta_error_stack_7},
      "error.type" : "java.lang.AssertionError",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "span.kind" : "test",
      "test.final_status" : "fail",
      "test.framework" : "cucumber",
      "test.framework_version" : "7.22.0",
      "test.has_failed_all_retries" : "true",
      "test.is_retry" : "true",
      "test.module" : "Maven Smoke Tests Project maven-surefire-plugin default-test",
      "test.name" : "Basic Arithmetic - Addition",
      "test.retry_reason" : "auto_test_retry",
      "test.status" : "fail",
      "test.suite" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic",
      "test.type" : "test",
      "test_session.name" : "mvn -B test"
    },
    "metrics" : {
      "_dd.host.vcpu_count" : ${content_metrics__dd_host_vcpu_count_8},
      "_dd.profiling.enabled" : 0,
      "_dd.trace_span_attribute_schema" : 0,
      "process_id" : ${content_metrics_process_id_2}
    },
    "name" : "cucumber.test",
    "parent_id" : ${content_parent_id_6},
    "resource" : "classpath:datadog/smoke/basic_arithmetic.feature:Basic Arithmetic.Basic Arithmetic - Addition",
    "service" : "test-maven-service",
    "span_id" : ${content_parent_id_5},
    "start" : ${content_start_22},
    "test_module_id" : ${content_test_module_id},
    "test_session_id" : ${content_test_session_id},
    "test_suite_id" : ${content_test_suite_id},
    "trace_id" : ${content_trace_id_5}
  },
  "type" : "test",
  "version" : 2
}, {
  "content" : {
    "duration" : ${content_duration_23},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_23},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[8]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.the_result_is(int)",
      "step.name" : "the result is {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id},
    "resource" : "the result is {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_15},
    "start" : ${content_start_23},
    "trace_id" : ${content_trace_id}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_24},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_24},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[8]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.the_result_is(int)",
      "step.name" : "the result is {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_2},
    "resource" : "the result is {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_16},
    "start" : ${content_start_24},
    "trace_id" : ${content_trace_id_2}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_25},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_25},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[8]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.the_result_is(int)",
      "step.name" : "the result is {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_3},
    "resource" : "the result is {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_17},
    "start" : ${content_start_25},
    "trace_id" : ${content_trace_id_3}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_26},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_26},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[8]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.the_result_is(int)",
      "step.name" : "the result is {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_4},
    "resource" : "the result is {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_18},
    "start" : ${content_start_26},
    "trace_id" : ${content_trace_id_4}
  },
  "type" : "span",
  "version" : 1
}, {
  "content" : {
    "duration" : ${content_duration_27},
    "error" : 0,
    "meta" : {
      "_dd.p.tid" : ${content_meta__dd_p_tid_27},
      "_dd.test.is_user_provided_service" : "true",
      "component" : "cucumber",
      "env" : "integration-test",
      "language" : "jvm",
      "library_version" : ${content_meta_library_version},
      "os.architecture" : ${content_meta_os_architecture},
      "os.platform" : ${content_meta_os_platform},
      "os.version" : ${content_meta_os_version},
      "runtime-id" : ${content_meta_runtime_id},
      "runtime.name" : ${content_meta_runtime_name},
      "runtime.vendor" : ${content_meta_runtime_vendor},
      "runtime.version" : ${content_meta_runtime_version},
      "step.arguments" : "[8]",
      "step.location" : "datadog.smoke.calculator.CalculatorSteps.the_result_is(int)",
      "step.name" : "the result is {int}",
      "step.type" : "io.cucumber.java.JavaStepDefinition"
    },
    "metrics" : { },
    "name" : "cucumber.step",
    "parent_id" : ${content_parent_id_5},
    "resource" : "the result is {int}",
    "service" : "test-maven-service",
    "span_id" : ${content_span_id_19},
    "start" : ${content_start_27},
    "trace_id" : ${content_trace_id_5}
  },
  "type" : "span",
  "version" : 1
} ]