package datadog.gradle.plugin.muzzle

import datadog.gradle.plugin.GradleFixture
import java.io.File

/**
 * Test fixture for muzzle plugin integration tests.
 * Extends GradleFixture with muzzle-specific functionality.
 */
internal class MuzzlePluginTestFixture(
  projectDir: File,
) : GradleFixture(projectDir) {

  /**
   * Writes the basic Gradle project structure for muzzle testing.
   * Creates a multi-project build with agent-bootstrap, agent-tooling, and instrumentation modules.
   */
  fun writeProject(instrumentationBuildScript: String) {
    file("settings.gradle").writeText(
      """
      rootProject.name = 'muzzle-e2e'
      include ':dd-java-agent:agent-bootstrap'
      include ':dd-java-agent:agent-tooling'
      include ':dd-java-agent:instrumentation:demo'
      """.trimIndent()
    )

    file("dd-java-agent/agent-bootstrap/build.gradle").writeText(
      """
      plugins {
        id 'java'
      }

      tasks.register('compileMain_java11Java')
      """.trimIndent()
    )

    file("dd-java-agent/agent-tooling/build.gradle").writeText(
      """
      plugins {
        id 'java'
      }
      """.trimIndent()
    )

    file("dd-java-agent/instrumentation/demo/build.gradle").writeText(instrumentationBuildScript.trimIndent())
  }

  /**
   * Writes a muzzle scan plugin that always passes.
   */
  fun writeNoopScanPlugin() {
    writeScanPlugin("// noop")
  }

  /**
   * Writes a muzzle scan plugin with custom assertion logic.
   *
   * @param assertionBody Java code to execute in the assertion method
   */
  fun writeScanPlugin(assertionBody: String) {
    file("dd-java-agent/instrumentation/demo/src/main/java/datadog/trace/agent/tooling/muzzle/MuzzleVersionScanPlugin.java")
      .writeText(
        """
        package datadog.trace.agent.tooling.muzzle;

        public final class MuzzleVersionScanPlugin {
          private MuzzleVersionScanPlugin() {}

          public static void assertInstrumentationMuzzled(
              ClassLoader instrumentationClassLoader,
              ClassLoader testApplicationClassLoader,
              boolean assertPass,
              String muzzleDirective) {
            $assertionBody
          }
        }
        """.trimIndent()
      )
  }

  /**
   * Finds the single JUnit XML report generated by muzzle tests.
   * Throws if zero or multiple reports are found.
   */
  fun findSingleMuzzleJUnitReport(): File {
    val reports = projectDir.walkTopDown()
      .filter { it.isFile && it.name.startsWith("TEST-muzzle-") && it.extension == "xml" }
      .toList()
    require(reports.size == 1) {
      "Expected exactly one JUnit muzzle report, but found ${reports.size}"
    }
    return reports.single()
  }

  /**
   * Returns the path to a muzzle result file for the given task name.
   */
  fun resultFile(taskName: String) =
    projectDir.toPath().resolve("dd-java-agent/instrumentation/demo/build/reports/$taskName.txt")
}
