package datadog.gradle.plugin.muzzle

import datadog.gradle.plugin.GradleFixture
import org.intellij.lang.annotations.Language
import java.io.File

/**
 * Test fixture for muzzle plugin integration tests.
 * Extends GradleFixture with muzzle-specific functionality.
 */
open class MuzzlePluginTestFixture : GradleFixture() {
  /**
   * Writes the basic Gradle project structure for muzzle testing.
   * Creates a multi-project build with agent-bootstrap, agent-tooling, and instrumentation modules.
   */
  fun writeProject(@Language("kotlin") instrumentationBuildScript: String) {
    writeSettings(
      """
      rootProject.name = "muzzle-e2e"
      """
    )

    addSubproject("dd-java-agent:agent-bootstrap",
      """
      plugins {
        id("java")
      }

      tasks.register("compileMain_java11Java")
      """
    )

    addSubproject("dd-java-agent:agent-tooling",
      """
      plugins {
        id("java")
      }
      """
    )

    addSubproject("dd-java-agent:instrumentation:demo", instrumentationBuildScript)
  }

  /** Writes an aggregation project with optional instrumentation report producers. */
  fun writeAggregationProject(vararg producers: String) {
    addSubproject("dd-java-agent:instrumentation",
      """
      plugins {
        id("java")
        id("dd-trace-java.muzzle-report-aggregation")
      }
      layout.buildDirectory.set(layout.projectDirectory.dir("relocated/build"))
      muzzleReports.reportFile.set(layout.buildDirectory.file("muzzle-deps-results/dd-java-agent_instrumentation.csv"))
      dependencies {
        ${producers.joinToString("\n") { "implementation(project(\":dd-java-agent:instrumentation:$it\"))" }}
      }
      tasks.register("muzzleInstrumentationReport") { dependsOn(tasks.named("aggregateMuzzleReports")) }
      """
    )
    writeRootProject(
      """
      plugins { id("dd-trace-java.muzzle-report-aggregation") apply false }
      layout.buildDirectory.set(layout.projectDirectory.dir("relocated/build"))
      """
    )
  }

  /**
   * Writes a muzzle scan plugin that always passes.
   */
  fun writeNoopScanPlugin() {
    writeScanPlugin("// noop")
  }

  /**
   * Writes a muzzle scan plugin with custom assertion logic.
   * The plugin is written to the agent-tooling project where it belongs.
   *
   * @param assertionBody Java code to execute in the assertion method
   */
  fun writeScanPlugin(@Language("JAVA") assertionBody: String) {
    writeJavaSource(
      "datadog.trace.agent.tooling.muzzle.MuzzleVersionScanPlugin",
      // language=JAVA
      """
      package datadog.trace.agent.tooling.muzzle;

      import static java.util.Collections.singleton;

      import java.util.Set;

      public final class MuzzleVersionScanPlugin {
        private MuzzleVersionScanPlugin() {}

        public static Set<String> listInstrumentationNames(
            ClassLoader instrumentationClassLoader, String muzzleDirective) {
          return singleton("test-instrumentation");
        }

        public static void assertInstrumentationMuzzled(
            ClassLoader instrumentationClassLoader,
            ClassLoader testApplicationClassLoader,
            boolean assertPass,
            String muzzleDirective) {
          $assertionBody
        }
      }
      """,
      projectPath = "dd-java-agent:agent-tooling",
    )
  }

  /**
   * Finds the single JUnit XML report generated by muzzle tests.
   * Throws if zero or multiple reports are found.
   */
  fun findSingleMuzzleJUnitReport(): File {
    val reports = projectDir.walkTopDown()
      .filter { it.isFile && it.name.startsWith("TEST-muzzle-") && it.extension == "xml" }
      .toList()
    require(reports.size == 1) {
      "Expected exactly one JUnit muzzle report, but found ${reports.size}"
    }
    return reports.single()
  }

  /**
   * Returns the path to a muzzle result file for the given task name.
   */
  fun resultFile(taskName: String) =
    projectDir.toPath().resolve("dd-java-agent/instrumentation/demo/build/reports/$taskName.txt")
}
