import {spawn} from 'node:child_process';
import {mkdtemp,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
const output=resolve(process.argv[2] || 'tools/instrumentation-coverage/cartography/build/report');
const expected=JSON.parse(await readFile(join(output,'report.json'),'utf8'));
const profile=await mkdtemp(join(tmpdir(),'cartography-browser-'));
const browser=spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--disable-background-networking','--disable-component-update','--no-first-run','--no-default-browser-check','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{stdio:['ignore','ignore','pipe']});
let socket;
try {
 const endpoint=await new Promise((resolve,reject)=>{let stderr='';const timer=setTimeout(()=>reject(Error('Startup timeout')),20000);browser.stderr.on('data',chunk=>{stderr+=chunk;const match=stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(match){clearTimeout(timer);resolve(match[1]);}});browser.on('error',reject);});
 const pages=await (await fetch(endpoint.replace('ws:','http:').replace(/\/devtools\/browser\/.*/,'/json/list'))).json();
 socket=new WebSocket(pages.find(p=>p.type==='page').webSocketDebuggerUrl);await new Promise(r=>socket.addEventListener('open',r,{once:true}));
 let serial=0;const pending=new Map();socket.addEventListener('message',e=>{const d=JSON.parse(e.data);if(d.id){const p=pending.get(d.id);pending.delete(d.id);d.error?p.reject(d.error):p.resolve(d.result);}});
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;const timer=setTimeout(()=>{pending.delete(id);reject(Error('Browser command timed out: '+method));},45000);pending.set(id,{resolve:r=>{clearTimeout(timer);resolve(r);},reject:e=>{clearTimeout(timer);reject(e);}});socket.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 await send('Emulation.setDeviceMetricsOverride',{width:1600,height:1000,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:pathToFileURL(join(output,'joined-report.html')).href});
 for(let i=0;i<150;i++){if(await evaluate("document.querySelectorAll('.flow-card').length>0"))break;await new Promise(r=>setTimeout(r,100));}
 assert.equal(await evaluate("document.querySelectorAll('.flow-card').length"),expected.flows.length);
 assert.ok(await evaluate(`document.getElementById('stats').textContent.includes('${expected.testExecution.passed} passed')`));
 assert.equal(await evaluate("document.querySelectorAll('.statistical-table tr').length"),expected.statisticalAttribution.testAccounting.total+1);
 assert.equal(await evaluate("document.getElementById('load-error').textContent"),'');
 assert.ok(await evaluate("document.querySelector('.statistical-table').textContent.includes('no library observations')"));
 assert.ok(await evaluate("document.querySelector('.statistical-table').textContent.includes('no collection')"));
 assert.equal(await evaluate("getComputedStyle(document.querySelector('.key.context')).backgroundColor"),'rgb(8, 127, 91)');
 assert.equal(await evaluate("document.getElementById('flows').textContent.includes('Representative:')"),false);
 assert.ok(await evaluate("document.getElementById('flows').textContent.includes('Reject a null async request')"));
 const shot=await send('Page.captureScreenshot',{format:'png'});await writeFile(join(output,'overview.png'),Buffer.from(shot.data,'base64'));
 await evaluate("[...document.querySelectorAll('.flow-card')].find(c=>parseInt(c.querySelector('.flow-meta span:last-child').textContent)>0).click()");
 assert.ok(await evaluate("document.getElementById('establish-flow').textContent.includes('Why this name?')"));
 assert.equal(await evaluate("document.getElementById('collection-details').open"),false);
 assert.ok(await evaluate("document.getElementById('establish-flow').textContent.includes('Landmarks needing attention')"));
 await evaluate("window.savedTask=null;const original=URL.createObjectURL;URL.createObjectURL=b=>{window.taskBlob=b;return original(b);};document.addEventListener('click',e=>{if(e.target.matches('a[download]'))e.preventDefault();});const s=document.querySelector('[aria-label=\"Upstream example to adapt\"]');if(s.options.length>1){s.value='1';s.dispatchEvent(new Event('change'));}document.querySelector('#establish-flow .task-download').click()");
 const task=await evaluate("window.taskBlob.text().then(JSON.parse)");
 assert.equal(task.examples.length,1);assert.equal(task.selectedExample,task.examples[0].name);assert.ok(task.examples[0].landmarks.length);
 assert.ok(task.suggestedAction);assert.ok(task.selectedEvidence.testIds.length);
 assert.equal(await evaluate("[...document.querySelectorAll('.plan-context')].every(d=>!d.open)"),true);
 assert.equal(await evaluate("[...document.querySelectorAll('.plan-category:not(.plan-context)')].every(d=>d.open)"),true);
 assert.equal(Object.values(task.landmarkAssessment).flat().length,task.examples[0].landmarks.flatMap(s=>s.methods).length);
 assert.ok(task.landmarkAssessment.context.every(m=>m.state==='context'));
 assert.ok(task.landmarkAssessment.review.every(m=>['root','mixed'].includes(m.state)));
 await evaluate("document.getElementById('establish-flow').scrollIntoView()");
 const planShot=await send('Page.captureScreenshot',{format:'png'});await writeFile(join(output,'test-plan.png'),Buffer.from(planShot.data,'base64'));
 await evaluate("document.querySelector('.corridor-head').scrollIntoView()");
 const corridor=await send('Page.captureScreenshot',{format:'png'});await writeFile(join(output,'corridor.png'),Buffer.from(corridor.data,'base64'));
 await evaluate("document.querySelector('.method-button').click()");
 assert.equal(await evaluate("document.getElementById('detail').hidden"),false);
 assert.ok(await evaluate("document.getElementById('detail').textContent.includes('Direct callees')"));
 await evaluate("document.getElementById('detail').scrollIntoView()");
 const detail=await send('Page.captureScreenshot',{format:'png'});await writeFile(join(output,'method-detail.png'),Buffer.from(detail.data,'base64'));
 await evaluate("document.querySelectorAll('.test-buttons .test-button')[1].click();document.querySelector('#establish-flow .task-download').click()");
 const scopedTask=await evaluate("window.taskBlob.text().then(JSON.parse)");assert.equal(scopedTask.selectedEvidence.testIds.length,1);assert.equal(scopedTask.selectedExample,task.selectedExample);
 await evaluate("[...document.querySelectorAll('.flow-card')].find(c=>parseInt(c.querySelector('.flow-meta span:last-child').textContent)===0).click();document.querySelector('#establish-flow .task-download').click()");
 const absentTask=await evaluate("window.taskBlob.text().then(JSON.parse)");assert.equal(absentTask.suggestedAction,'ADD_OR_IDENTIFY_SCENARIO');assert.equal(absentTask.selectedEvidence.testIds.length,0);
 console.log(`Browser passed: ${expected.flows.length} families, ${expected.statisticalAttribution.testAccounting.total} accounted test results, method selection and static neighborhood.`);
} finally {socket?.close();browser.kill();}
