name: Feature Request (Low Priority)
description: Create a public Feature Request. Note that these may not be addressed as quickly as the helpdesk and that looking up account information will be difficult.
title: "[FEATURE]: "
labels: "type: feature request"
body:
  - type: input
    attributes:
      label: Library Name
      description: "If your feature request is to add instrumentation support for a library please provide the name here"
      #placeholder: "TODO: Provide a sample Java library name"
    validations:
      required: false

  - type: input
    attributes:
      label: Library Version(s)
      description: "If your feature request is to add instrumentation support for a library please provide the version you use"
      placeholder: 1.2
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: |
        Please add a clear and concise description of your problem.
        E.g. I'm unable to instrument my database queries...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
    validations:
      required: false
