package com.datadog.debugger.agent;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/** Used for ignore coverage for JaCoCo on some method generated by IDE or code generator */
@Retention(RetentionPolicy.RUNTIME)
public @interface Generated {}
