plugins {
  id 'dd-trace-java.module.instrumentation'
}

muzzle {
  pass {
    group = 'com.microsoft.azure.functions'
    module = 'azure-functions-java-spi'
    versions = '[1.0.0,)'
    extraDependency 'com.microsoft.azure.functions:azure-functions-java-core-library:1.2.0'
  }
}

addTestSuiteForDir('latestDepTest', 'test')

dependencies {
  compileOnly group: 'com.microsoft.azure.functions', name: 'azure-functions-java-core-library', version: '1.2.0'
  compileOnly group: 'com.microsoft.azure.functions', name: 'azure-functions-java-spi', version: '1.0.0'

  testImplementation group: 'com.microsoft.azure.functions', name: 'azure-functions-java-core-library', version: '1.2.0'
  testImplementation group: 'com.microsoft.azure.functions', name: 'azure-functions-java-spi', version: '1.0.0'
  testImplementation libs.bundles.mockito

  latestDepTestImplementation group: 'com.microsoft.azure.functions', name: 'azure-functions-java-core-library', version: '+'
  latestDepTestImplementation group: 'com.microsoft.azure.functions', name: 'azure-functions-java-spi', version: '+'
}
