// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

public final class Message {
  private Message() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface MyMessageOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:MyMessage)
      com.google.protobuf.MessageOrBuilder {

    /** <code>optional string id = 1;</code> */
    java.lang.String getId();
    /** <code>optional string id = 1;</code> */
    com.google.protobuf.ByteString getIdBytes();

    /** <code>optional string value = 2;</code> */
    java.lang.String getValue();
    /** <code>optional string value = 2;</code> */
    com.google.protobuf.ByteString getValueBytes();

    /** <code>repeated .OtherMessage other_message = 3;</code> */
    java.util.List<OtherMessageOuterClass.OtherMessage> getOtherMessageList();
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    OtherMessageOuterClass.OtherMessage getOtherMessage(int index);
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    int getOtherMessageCount();
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    java.util.List<? extends OtherMessageOuterClass.OtherMessageOrBuilder>
        getOtherMessageOrBuilderList();
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    OtherMessageOuterClass.OtherMessageOrBuilder getOtherMessageOrBuilder(int index);
  }
  /** Protobuf type {@code MyMessage} */
  public static final class MyMessage extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:MyMessage)
      MyMessageOrBuilder {
    // Use MyMessage.newBuilder() to construct.
    private MyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private MyMessage() {
      id_ = "";
      value_ = "";
      otherMessage_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private MyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default:
              {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
            case 10:
              {
                java.lang.String s = input.readStringRequireUtf8();

                id_ = s;
                break;
              }
            case 18:
              {
                java.lang.String s = input.readStringRequireUtf8();

                value_ = s;
                break;
              }
            case 26:
              {
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  otherMessage_ = new java.util.ArrayList<OtherMessageOuterClass.OtherMessage>();
                  mutable_bitField0_ |= 0x00000004;
                }
                otherMessage_.add(
                    input.readMessage(
                        OtherMessageOuterClass.OtherMessage.parser(), extensionRegistry));
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          otherMessage_ = java.util.Collections.unmodifiableList(otherMessage_);
        }
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Message.internal_static_MyMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Message.internal_static_MyMessage_fieldAccessorTable.ensureFieldAccessorsInitialized(
          Message.MyMessage.class, Message.MyMessage.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /** <code>optional string id = 1;</code> */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /** <code>optional string id = 1;</code> */
    public com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile java.lang.Object value_;
    /** <code>optional string value = 2;</code> */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /** <code>optional string value = 2;</code> */
    public com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OTHER_MESSAGE_FIELD_NUMBER = 3;
    private java.util.List<OtherMessageOuterClass.OtherMessage> otherMessage_;
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    public java.util.List<OtherMessageOuterClass.OtherMessage> getOtherMessageList() {
      return otherMessage_;
    }
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    public java.util.List<? extends OtherMessageOuterClass.OtherMessageOrBuilder>
        getOtherMessageOrBuilderList() {
      return otherMessage_;
    }
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    public int getOtherMessageCount() {
      return otherMessage_.size();
    }
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    public OtherMessageOuterClass.OtherMessage getOtherMessage(int index) {
      return otherMessage_.get(index);
    }
    /** <code>repeated .OtherMessage other_message = 3;</code> */
    public OtherMessageOuterClass.OtherMessageOrBuilder getOtherMessageOrBuilder(int index) {
      return otherMessage_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      for (int i = 0; i < otherMessage_.size(); i++) {
        output.writeMessage(3, otherMessage_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      for (int i = 0; i < otherMessage_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, otherMessage_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Message.MyMessage)) {
        return super.equals(obj);
      }
      Message.MyMessage other = (Message.MyMessage) obj;

      boolean result = true;
      result = result && getId().equals(other.getId());
      result = result && getValue().equals(other.getValue());
      result = result && getOtherMessageList().equals(other.getOtherMessageList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      if (getOtherMessageCount() > 0) {
        hash = (37 * hash) + OTHER_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getOtherMessageList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Message.MyMessage parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Message.MyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Message.MyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Message.MyMessage parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Message.MyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static Message.MyMessage parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static Message.MyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static Message.MyMessage parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static Message.MyMessage parseFrom(com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static Message.MyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(Message.MyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code MyMessage} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:MyMessage)
        Message.MyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return Message.internal_static_MyMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Message.internal_static_MyMessage_fieldAccessorTable.ensureFieldAccessorsInitialized(
            Message.MyMessage.class, Message.MyMessage.Builder.class);
      }

      // Construct using Message.MyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getOtherMessageFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        id_ = "";

        value_ = "";

        if (otherMessageBuilder_ == null) {
          otherMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          otherMessageBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return Message.internal_static_MyMessage_descriptor;
      }

      public Message.MyMessage getDefaultInstanceForType() {
        return Message.MyMessage.getDefaultInstance();
      }

      public Message.MyMessage build() {
        Message.MyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message.MyMessage buildPartial() {
        Message.MyMessage result = new Message.MyMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.value_ = value_;
        if (otherMessageBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            otherMessage_ = java.util.Collections.unmodifiableList(otherMessage_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.otherMessage_ = otherMessage_;
        } else {
          result.otherMessage_ = otherMessageBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message.MyMessage) {
          return mergeFrom((Message.MyMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message.MyMessage other) {
        if (other == Message.MyMessage.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (otherMessageBuilder_ == null) {
          if (!other.otherMessage_.isEmpty()) {
            if (otherMessage_.isEmpty()) {
              otherMessage_ = other.otherMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureOtherMessageIsMutable();
              otherMessage_.addAll(other.otherMessage_);
            }
            onChanged();
          }
        } else {
          if (!other.otherMessage_.isEmpty()) {
            if (otherMessageBuilder_.isEmpty()) {
              otherMessageBuilder_.dispose();
              otherMessageBuilder_ = null;
              otherMessage_ = other.otherMessage_;
              bitField0_ = (bitField0_ & ~0x00000004);
              otherMessageBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                      ? getOtherMessageFieldBuilder()
                      : null;
            } else {
              otherMessageBuilder_.addAllMessages(other.otherMessage_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message.MyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message.MyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object id_ = "";
      /** <code>optional string id = 1;</code> */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>optional string id = 1;</code> */
      public com.google.protobuf.ByteString getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>optional string id = 1;</code> */
      public Builder setId(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        id_ = value;
        onChanged();
        return this;
      }
      /** <code>optional string id = 1;</code> */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /** <code>optional string id = 1;</code> */
      public Builder setIdBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /** <code>optional string value = 2;</code> */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /** <code>optional string value = 2;</code> */
      public com.google.protobuf.ByteString getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /** <code>optional string value = 2;</code> */
      public Builder setValue(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        value_ = value;
        onChanged();
        return this;
      }
      /** <code>optional string value = 2;</code> */
      public Builder clearValue() {

        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /** <code>optional string value = 2;</code> */
      public Builder setValueBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        value_ = value;
        onChanged();
        return this;
      }

      private java.util.List<OtherMessageOuterClass.OtherMessage> otherMessage_ =
          java.util.Collections.emptyList();

      private void ensureOtherMessageIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          otherMessage_ =
              new java.util.ArrayList<OtherMessageOuterClass.OtherMessage>(otherMessage_);
          bitField0_ |= 0x00000004;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              OtherMessageOuterClass.OtherMessage,
              OtherMessageOuterClass.OtherMessage.Builder,
              OtherMessageOuterClass.OtherMessageOrBuilder>
          otherMessageBuilder_;

      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public java.util.List<OtherMessageOuterClass.OtherMessage> getOtherMessageList() {
        if (otherMessageBuilder_ == null) {
          return java.util.Collections.unmodifiableList(otherMessage_);
        } else {
          return otherMessageBuilder_.getMessageList();
        }
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public int getOtherMessageCount() {
        if (otherMessageBuilder_ == null) {
          return otherMessage_.size();
        } else {
          return otherMessageBuilder_.getCount();
        }
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public OtherMessageOuterClass.OtherMessage getOtherMessage(int index) {
        if (otherMessageBuilder_ == null) {
          return otherMessage_.get(index);
        } else {
          return otherMessageBuilder_.getMessage(index);
        }
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder setOtherMessage(int index, OtherMessageOuterClass.OtherMessage value) {
        if (otherMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherMessageIsMutable();
          otherMessage_.set(index, value);
          onChanged();
        } else {
          otherMessageBuilder_.setMessage(index, value);
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder setOtherMessage(
          int index, OtherMessageOuterClass.OtherMessage.Builder builderForValue) {
        if (otherMessageBuilder_ == null) {
          ensureOtherMessageIsMutable();
          otherMessage_.set(index, builderForValue.build());
          onChanged();
        } else {
          otherMessageBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder addOtherMessage(OtherMessageOuterClass.OtherMessage value) {
        if (otherMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherMessageIsMutable();
          otherMessage_.add(value);
          onChanged();
        } else {
          otherMessageBuilder_.addMessage(value);
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder addOtherMessage(int index, OtherMessageOuterClass.OtherMessage value) {
        if (otherMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOtherMessageIsMutable();
          otherMessage_.add(index, value);
          onChanged();
        } else {
          otherMessageBuilder_.addMessage(index, value);
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder addOtherMessage(OtherMessageOuterClass.OtherMessage.Builder builderForValue) {
        if (otherMessageBuilder_ == null) {
          ensureOtherMessageIsMutable();
          otherMessage_.add(builderForValue.build());
          onChanged();
        } else {
          otherMessageBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder addOtherMessage(
          int index, OtherMessageOuterClass.OtherMessage.Builder builderForValue) {
        if (otherMessageBuilder_ == null) {
          ensureOtherMessageIsMutable();
          otherMessage_.add(index, builderForValue.build());
          onChanged();
        } else {
          otherMessageBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder addAllOtherMessage(
          java.lang.Iterable<? extends OtherMessageOuterClass.OtherMessage> values) {
        if (otherMessageBuilder_ == null) {
          ensureOtherMessageIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, otherMessage_);
          onChanged();
        } else {
          otherMessageBuilder_.addAllMessages(values);
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder clearOtherMessage() {
        if (otherMessageBuilder_ == null) {
          otherMessage_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          otherMessageBuilder_.clear();
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public Builder removeOtherMessage(int index) {
        if (otherMessageBuilder_ == null) {
          ensureOtherMessageIsMutable();
          otherMessage_.remove(index);
          onChanged();
        } else {
          otherMessageBuilder_.remove(index);
        }
        return this;
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public OtherMessageOuterClass.OtherMessage.Builder getOtherMessageBuilder(int index) {
        return getOtherMessageFieldBuilder().getBuilder(index);
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public OtherMessageOuterClass.OtherMessageOrBuilder getOtherMessageOrBuilder(int index) {
        if (otherMessageBuilder_ == null) {
          return otherMessage_.get(index);
        } else {
          return otherMessageBuilder_.getMessageOrBuilder(index);
        }
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public java.util.List<? extends OtherMessageOuterClass.OtherMessageOrBuilder>
          getOtherMessageOrBuilderList() {
        if (otherMessageBuilder_ != null) {
          return otherMessageBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(otherMessage_);
        }
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public OtherMessageOuterClass.OtherMessage.Builder addOtherMessageBuilder() {
        return getOtherMessageFieldBuilder()
            .addBuilder(OtherMessageOuterClass.OtherMessage.getDefaultInstance());
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public OtherMessageOuterClass.OtherMessage.Builder addOtherMessageBuilder(int index) {
        return getOtherMessageFieldBuilder()
            .addBuilder(index, OtherMessageOuterClass.OtherMessage.getDefaultInstance());
      }
      /** <code>repeated .OtherMessage other_message = 3;</code> */
      public java.util.List<OtherMessageOuterClass.OtherMessage.Builder>
          getOtherMessageBuilderList() {
        return getOtherMessageFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              OtherMessageOuterClass.OtherMessage,
              OtherMessageOuterClass.OtherMessage.Builder,
              OtherMessageOuterClass.OtherMessageOrBuilder>
          getOtherMessageFieldBuilder() {
        if (otherMessageBuilder_ == null) {
          otherMessageBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<
                  OtherMessageOuterClass.OtherMessage,
                  OtherMessageOuterClass.OtherMessage.Builder,
                  OtherMessageOuterClass.OtherMessageOrBuilder>(
                  otherMessage_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          otherMessage_ = null;
        }
        return otherMessageBuilder_;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyMessage)
    }

    // @@protoc_insertion_point(class_scope:MyMessage)
    private static final Message.MyMessage DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new Message.MyMessage();
    }

    public static Message.MyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyMessage> PARSER =
        new com.google.protobuf.AbstractParser<MyMessage>() {
          public MyMessage parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new MyMessage(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<MyMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyMessage> getParserForType() {
      return PARSER;
    }

    public Message.MyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_MyMessage_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\032\023other_message.proto\"L\n\t"
          + "MyMessage\022\n\n\002id\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\022$\n\r"
          + "other_message\030\003 \003(\0132\r.OtherMessageb\006prot"
          + "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          OtherMessageOuterClass.getDescriptor(),
        },
        assigner);
    internal_static_MyMessage_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_MyMessage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_MyMessage_descriptor,
            new java.lang.String[] {
              "Id", "Value", "OtherMessage",
            });
    OtherMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
