package datadog.trace.api;

import datadog.trace.api.interceptor.MutableSpan;
import datadog.trace.api.interceptor.TraceInterceptor;

/** A class with Datadog tracer features. */
public interface Tracer {

  /** Get the trace id of the active trace. Returns 0 if there is no active trace. */
  String getTraceId();

  /**
   * Get the span id of the active span of the active trace. Returns 0 if there is no active trace.
   */
  String getSpanId();

  /**
   * Add a new interceptor to the tracer. Interceptors with duplicate priority to existing ones are
   * ignored.
   *
   * @param traceInterceptor
   * @return false if an interceptor with same priority exists.
   */
  boolean addTraceInterceptor(TraceInterceptor traceInterceptor);

  Blackhole muteTracing();

  interface Blackhole extends AutoCloseable {
    @Override
    void close();
  }

  /** Returns the active span for the trace fragment */
  MutableSpan getActiveMutableSpan();

  /**
   * Returns the root span for the current trace fragment. In the context of distributed tracing
   * this method returns the root span only for the fragment generated by the currently traced
   * application.
   *
   * @return The root span for the current trace fragment.
   */
  MutableSpan getLocalRootSpan();

  /**
   * Returns the root span for the trace fragment to which the mutable span belongs. In the context
   * of distributed tracing this method returns the root span only for the fragment generated by the
   * currently traced application.
   *
   * @return The root span for the current trace fragment.
   */
  MutableSpan getLocalRootSpan(MutableSpan mutableSpan);

  /**
   * Converts an OpenTelemetry Span or OpenTracing Span to a MutableSpan.
   *
   * @param span
   * @throws IllegalArgumentException if passed object is null or not an OpenTelemetry or
   *     OpenTracing span
   */
  MutableSpan toMutableSpan(Object span) throws IllegalArgumentException;
}
