FROM scratch
COPY dd-java-agent.jar /binaries/
COPY LIBRARY_VERSION /binaries/
COPY LIBDDWAF_VERSION /binaries/
COPY APPSEC_VERSION /binaries/
COPY IAST_VERSION /binaries/
COPY APPSEC_EVENT_RULES_VERSION /binaries/
