apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: default
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      name: datadog-agent
      labels:
        app: datadog-agent
    spec:
      affinity: {}
      containers:
      - command:
        - ddapm-test-agent
        env:
        - name: SNAPSHOT_CI
          value: "0"
        - name: DD_APM_RECEIVER_SOCKET
          value: /var/run/datadog/apm.socket
        image: ghcr.io/datadog/dd-apm-test-agent/ddapm-test-agent:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 8126
          timeoutSeconds: 5
        name: trace-agent
        ports:
        - containerPort: 8126
          hostPort: 8126
          name: traceport
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/datadog
          name: apmsocket
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /var/run/datadog/
            type: DirectoryOrCreate
          name: dsdsocket
        - hostPath:
            path: /var/run/datadog/
            type: DirectoryOrCreate
          name: apmsocket
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 10%
    type: RollingUpdate
