plugins {
  id 'dd-trace-java.module.instrumentation'
}

muzzle {
  pass {
    coreJdk()
  }
}

tracerJava {
  addSourceSetFor(JavaVersion.VERSION_11)
}

testJvmConstraints {
  excludeJdk = ['SEMERU11', 'SEMERU17']
}

["compileMain_java11Java", "compileTestJava"].each { name ->
  tasks.named(name, JavaCompile) {
    it.options.compilerArgs.addAll(['-Xlint:all,-processing,-options,-path'])
  }
}
