package datadog.trace.bootstrap.instrumentation.java.lang.invoke;

/**
 * Transforms the bytecode of a lambda class generated by {@code
 * java.lang.invoke.InnerClassLambdaMetafactory} before it is defined, so the lambda can receive the
 * same field-injection and advice the agent applies to ordinary classes.
 *
 * <p>The implementation is registered by the agent installer via {@link
 * LambdaTransformerHolder#set(LambdaTransformer)} once the main class-file transformer is ready.
 */
public interface LambdaTransformer {
  /**
   * @param slashClassName internal (slash-separated) name of the generated lambda class
   * @param targetClass the class declaring the lambda (used to resolve the defining class loader)
   * @param classBytes the freshly generated lambda class bytes
   * @return the transformed bytes, or {@code null}/the original bytes if unchanged
   */
  byte[] transform(String slashClassName, Class<?> targetClass, byte[] classBytes);
}
