import java.time.Duration
import java.time.temporal.ChronoUnit

plugins {
  id 'com.gradleup.shadow'
  id 'dd-trace-java.module.smoke-test'
}

description = 'Gradle Daemon Instrumentation Smoke Tests.'

dependencies {
  testImplementation gradleTestKit()
  testImplementation project(':dd-smoke-tests:backend-mock')
  testImplementation project(':internal-api')
  testImplementation project(':dd-java-agent:agent-ci-visibility:civisibility-test-fixtures')
}

tasks.named("test", Test) {
  // Gradle 4.10.3's native-platform crashes on Linux when restoring non-ASCII environment values, so remove all non-ASCII chars.
  ["CI_COMMIT_TITLE", "CI_COMMIT_MESSAGE", "CI_COMMIT_DESCRIPTION"].each { name ->
    String value = environment[name]
    if (value != null) {
      environment[name] = value.replaceAll("[^\\p{ASCII}]", "")
    }
  }

  testLogging {
    events "passed", "skipped", "failed", "standardOut", "standardError"
  }

  // Overriding the default timeout as Gradle smoke tests might run for a longer duration.
  timeout = Duration.of(25, ChronoUnit.MINUTES)

  if (project.hasProperty("mavenRepositoryProxy")) {
    // propagate proxy URL to tests, to then propagate it to nested Gradle builds
    environment "MAVEN_REPOSITORY_PROXY", project.property("mavenRepositoryProxy")
  }
}
