// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: other_message.proto

public final class OtherMessageOuterClass {
  private OtherMessageOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface OtherMessageOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:OtherMessage)
      com.google.protobuf.MessageOrBuilder {

    /** <code>repeated string name = 1;</code> */
    java.util.List<java.lang.String> getNameList();
    /** <code>repeated string name = 1;</code> */
    int getNameCount();
    /** <code>repeated string name = 1;</code> */
    java.lang.String getName(int index);
    /** <code>repeated string name = 1;</code> */
    com.google.protobuf.ByteString getNameBytes(int index);

    /** <code>optional int32 age = 2;</code> */
    int getAge();
  }
  /** Protobuf type {@code OtherMessage} */
  public static final class OtherMessage extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:OtherMessage)
      OtherMessageOrBuilder {
    // Use OtherMessage.newBuilder() to construct.
    private OtherMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private OtherMessage() {
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      age_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private OtherMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default:
              {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
            case 10:
              {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  name_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                name_.add(s);
                break;
              }
            case 16:
              {
                age_ = input.readInt32();
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = name_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return OtherMessageOuterClass.internal_static_OtherMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OtherMessageOuterClass.internal_static_OtherMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              OtherMessageOuterClass.OtherMessage.class,
              OtherMessageOuterClass.OtherMessage.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList name_;
    /** <code>repeated string name = 1;</code> */
    public com.google.protobuf.ProtocolStringList getNameList() {
      return name_;
    }
    /** <code>repeated string name = 1;</code> */
    public int getNameCount() {
      return name_.size();
    }
    /** <code>repeated string name = 1;</code> */
    public java.lang.String getName(int index) {
      return name_.get(index);
    }
    /** <code>repeated string name = 1;</code> */
    public com.google.protobuf.ByteString getNameBytes(int index) {
      return name_.getByteString(index);
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /** <code>optional int32 age = 2;</code> */
    public int getAge() {
      return age_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      for (int i = 0; i < name_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_.getRaw(i));
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += computeStringSizeNoTag(name_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream.computeInt32Size(2, age_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof OtherMessageOuterClass.OtherMessage)) {
        return super.equals(obj);
      }
      OtherMessageOuterClass.OtherMessage other = (OtherMessageOuterClass.OtherMessage) obj;

      boolean result = true;
      result = result && getNameList().equals(other.getNameList());
      result = result && (getAge() == other.getAge());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getNameCount() > 0) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getNameList().hashCode();
      }
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static OtherMessageOuterClass.OtherMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static OtherMessageOuterClass.OtherMessage parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static OtherMessageOuterClass.OtherMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(OtherMessageOuterClass.OtherMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /** Protobuf type {@code OtherMessage} */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:OtherMessage)
        OtherMessageOuterClass.OtherMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return OtherMessageOuterClass.internal_static_OtherMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return OtherMessageOuterClass.internal_static_OtherMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                OtherMessageOuterClass.OtherMessage.class,
                OtherMessageOuterClass.OtherMessage.Builder.class);
      }

      // Construct using OtherMessageOuterClass.OtherMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
      }

      public Builder clear() {
        super.clear();
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        age_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return OtherMessageOuterClass.internal_static_OtherMessage_descriptor;
      }

      public OtherMessageOuterClass.OtherMessage getDefaultInstanceForType() {
        return OtherMessageOuterClass.OtherMessage.getDefaultInstance();
      }

      public OtherMessageOuterClass.OtherMessage build() {
        OtherMessageOuterClass.OtherMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public OtherMessageOuterClass.OtherMessage buildPartial() {
        OtherMessageOuterClass.OtherMessage result = new OtherMessageOuterClass.OtherMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = name_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.name_ = name_;
        result.age_ = age_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof OtherMessageOuterClass.OtherMessage) {
          return mergeFrom((OtherMessageOuterClass.OtherMessage) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(OtherMessageOuterClass.OtherMessage other) {
        if (other == OtherMessageOuterClass.OtherMessage.getDefaultInstance()) return this;
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        OtherMessageOuterClass.OtherMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (OtherMessageOuterClass.OtherMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.LazyStringList name_ =
          com.google.protobuf.LazyStringArrayList.EMPTY;

      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000001;
        }
      }
      /** <code>repeated string name = 1;</code> */
      public com.google.protobuf.ProtocolStringList getNameList() {
        return name_.getUnmodifiableView();
      }
      /** <code>repeated string name = 1;</code> */
      public int getNameCount() {
        return name_.size();
      }
      /** <code>repeated string name = 1;</code> */
      public java.lang.String getName(int index) {
        return name_.get(index);
      }
      /** <code>repeated string name = 1;</code> */
      public com.google.protobuf.ByteString getNameBytes(int index) {
        return name_.getByteString(index);
      }
      /** <code>repeated string name = 1;</code> */
      public Builder setName(int index, java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      /** <code>repeated string name = 1;</code> */
      public Builder addName(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      /** <code>repeated string name = 1;</code> */
      public Builder addAllName(java.lang.Iterable<java.lang.String> values) {
        ensureNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, name_);
        onChanged();
        return this;
      }
      /** <code>repeated string name = 1;</code> */
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /** <code>repeated string name = 1;</code> */
      public Builder addNameBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);
        ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }

      private int age_;
      /** <code>optional int32 age = 2;</code> */
      public int getAge() {
        return age_;
      }
      /** <code>optional int32 age = 2;</code> */
      public Builder setAge(int value) {

        age_ = value;
        onChanged();
        return this;
      }
      /** <code>optional int32 age = 2;</code> */
      public Builder clearAge() {

        age_ = 0;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OtherMessage)
    }

    // @@protoc_insertion_point(class_scope:OtherMessage)
    private static final OtherMessageOuterClass.OtherMessage DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new OtherMessageOuterClass.OtherMessage();
    }

    public static OtherMessageOuterClass.OtherMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OtherMessage> PARSER =
        new com.google.protobuf.AbstractParser<OtherMessage>() {
          public OtherMessage parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new OtherMessage(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<OtherMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OtherMessage> getParserForType() {
      return PARSER;
    }

    public OtherMessageOuterClass.OtherMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_OtherMessage_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OtherMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\023other_message.proto\")\n\014OtherMessage\022\014\n"
          + "\004name\030\001 \003(\t\022\013\n\003age\030\002 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData, new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_OtherMessage_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_OtherMessage_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_OtherMessage_descriptor,
            new java.lang.String[] {
              "Name", "Age",
            });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
