plugins {
  id 'dd-trace-java.module.instrumentation'
}

muzzle {
  pass {
    group = "com.squareup.okhttp3"
    module = "okhttp"
    versions = "[3.0,)"
    assertInverse = true
  }
}

addTestSuiteForDir('latestDepTest', 'test')

def latestVersion = '3.+'

dependencies {
  compileOnly libs.okhttp3.minimum

  testImplementation(group: 'com.squareup.okhttp3', name: 'okhttp') {
    version {
      strictly "[${libs.versions.okhttp3.minimum.get()},4)"
      prefer libs.versions.okhttp3.minimum.get()
    }
  }
  testImplementation('com.squareup.okio:okio') {
    version {
      strictly '[1.6.0,2]'
      prefer '1.6.0'
    }
  }
  // Downgrade moshi to a previous version as moshi 1.2.0+ requires okio 1.8.0+
  testImplementation('com.squareup.moshi:moshi') {
    version {
      strictly '1.1.0'
    }
  }

  latestDepTestImplementation group: 'com.squareup.okhttp3', name: 'okhttp', version: latestVersion
  latestDepTestImplementation group: 'com.squareup.okio', name: 'okio', version: '1.+'

  testRuntimeOnly(project(':dd-java-agent:instrumentation:datadog:asm:iast-instrumenter'))
  testRuntimeOnly(project(':dd-java-agent:instrumentation:java:java-net:java-net-1.8'))
}
