/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

import java.util.ArrayList;
import java.util.List;

public class AppIntegrationsChange extends Payload {

  @com.squareup.moshi.Json(name = "integrations")
  private List<Integration> integrations = new ArrayList<Integration>();

  /**
   * Get integrations
   *
   * @return integrations
   */
  public List<Integration> getIntegrations() {
    return integrations;
  }

  /** Set integrations */
  public void setIntegrations(List<Integration> integrations) {
    this.integrations = integrations;
  }

  public AppIntegrationsChange integrations(List<Integration> integrations) {
    this.integrations = integrations;
    return this;
  }

  public AppIntegrationsChange addIntegrationsItem(Integration integrationsItem) {
    this.integrations.add(integrationsItem);
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppIntegrationsChange {\n");
    sb.append("    ").append(super.toString()).append("\n");
    sb.append("    integrations: ").append(integrations).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
