/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

public class Application {

  @com.squareup.moshi.Json(name = "env")
  private String env;

  @com.squareup.moshi.Json(name = "language_name")
  private String languageName;

  @com.squareup.moshi.Json(name = "language_version")
  private String languageVersion;

  @com.squareup.moshi.Json(name = "runtime_name")
  private String runtimeName;

  @com.squareup.moshi.Json(name = "runtime_patches")
  private String runtimePatches;

  @com.squareup.moshi.Json(name = "runtime_version")
  private String runtimeVersion;

  @com.squareup.moshi.Json(name = "service_name")
  private String serviceName;

  @com.squareup.moshi.Json(name = "service_version")
  private String serviceVersion;

  @com.squareup.moshi.Json(name = "tracer_version")
  private String tracerVersion;

  /**
   * Get env
   *
   * @return env
   */
  public String getEnv() {
    return env;
  }

  /** Set env */
  public void setEnv(String env) {
    this.env = env;
  }

  public Application env(String env) {
    this.env = env;
    return this;
  }

  /**
   * Get languageName
   *
   * @return languageName
   */
  public String getLanguageName() {
    return languageName;
  }

  /** Set languageName */
  public void setLanguageName(String languageName) {
    this.languageName = languageName;
  }

  public Application languageName(String languageName) {
    this.languageName = languageName;
    return this;
  }

  /**
   * Get languageVersion
   *
   * @return languageVersion
   */
  public String getLanguageVersion() {
    return languageVersion;
  }

  /** Set languageVersion */
  public void setLanguageVersion(String languageVersion) {
    this.languageVersion = languageVersion;
  }

  public Application languageVersion(String languageVersion) {
    this.languageVersion = languageVersion;
    return this;
  }

  /**
   * Get runtimeName
   *
   * @return runtimeName
   */
  public String getRuntimeName() {
    return runtimeName;
  }

  /** Set runtimeName */
  public void setRuntimeName(String runtimeName) {
    this.runtimeName = runtimeName;
  }

  public Application runtimeName(String runtimeName) {
    this.runtimeName = runtimeName;
    return this;
  }

  /**
   * Get runtimePatches
   *
   * @return runtimePatches
   */
  public String getRuntimePatches() {
    return runtimePatches;
  }

  /** Set runtimePatches */
  public void setRuntimePatches(String runtimePatches) {
    this.runtimePatches = runtimePatches;
  }

  public Application runtimePatches(String runtimePatches) {
    this.runtimePatches = runtimePatches;
    return this;
  }

  /**
   * Get runtimeVersion
   *
   * @return runtimeVersion
   */
  public String getRuntimeVersion() {
    return runtimeVersion;
  }

  /** Set runtimeVersion */
  public void setRuntimeVersion(String runtimeVersion) {
    this.runtimeVersion = runtimeVersion;
  }

  public Application runtimeVersion(String runtimeVersion) {
    this.runtimeVersion = runtimeVersion;
    return this;
  }

  /**
   * Get serviceName
   *
   * @return serviceName
   */
  public String getServiceName() {
    return serviceName;
  }

  /** Set serviceName */
  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public Application serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

  /**
   * Get serviceVersion
   *
   * @return serviceVersion
   */
  public String getServiceVersion() {
    return serviceVersion;
  }

  /** Set serviceVersion */
  public void setServiceVersion(String serviceVersion) {
    this.serviceVersion = serviceVersion;
  }

  public Application serviceVersion(String serviceVersion) {
    this.serviceVersion = serviceVersion;
    return this;
  }

  /**
   * Get tracerVersion
   *
   * @return tracerVersion
   */
  public String getTracerVersion() {
    return tracerVersion;
  }

  /** Set tracerVersion */
  public void setTracerVersion(String tracerVersion) {
    this.tracerVersion = tracerVersion;
  }

  public Application tracerVersion(String tracerVersion) {
    this.tracerVersion = tracerVersion;
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");

    sb.append("    env: ").append(env).append("\n");
    sb.append("    languageName: ").append(languageName).append("\n");
    sb.append("    languageVersion: ").append(languageVersion).append("\n");
    sb.append("    runtimeName: ").append(runtimeName).append("\n");
    sb.append("    runtimePatches: ").append(runtimePatches).append("\n");
    sb.append("    runtimeVersion: ").append(runtimeVersion).append("\n");
    sb.append("    serviceName: ").append(serviceName).append("\n");
    sb.append("    serviceVersion: ").append(serviceVersion).append("\n");
    sb.append("    tracerVersion: ").append(tracerVersion).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
