/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

import java.util.ArrayList;
import java.util.List;

public class AppStarted extends Payload {

  @com.squareup.moshi.Json(name = "configuration")
  private List<KeyValue> configuration = null;

  @com.squareup.moshi.Json(name = "dependencies")
  private List<Dependency> dependencies = new ArrayList<Dependency>();

  @com.squareup.moshi.Json(name = "integrations")
  private List<Integration> integrations = new ArrayList<Integration>();

  /**
   * Get _configuration
   *
   * @return _configuration
   */
  public List<KeyValue> getConfiguration() {
    return configuration;
  }

  /** Set _configuration */
  public void setConfiguration(List<KeyValue> configuration) {
    this.configuration = configuration;
  }

  public AppStarted _configuration(List<KeyValue> _configuration) {
    this.configuration = _configuration;
    return this;
  }

  public AppStarted addConfigurationItem(KeyValue _configurationItem) {
    this.configuration.add(_configurationItem);
    return this;
  }

  /**
   * Get dependencies
   *
   * @return dependencies
   */
  public List<Dependency> getDependencies() {
    return dependencies;
  }

  /** Set dependencies */
  public void setDependencies(List<Dependency> dependencies) {
    this.dependencies = dependencies;
  }

  public AppStarted dependencies(List<Dependency> dependencies) {
    this.dependencies = dependencies;
    return this;
  }

  public AppStarted addDependenciesItem(Dependency dependenciesItem) {
    this.dependencies.add(dependenciesItem);
    return this;
  }

  /**
   * Get integrations
   *
   * @return integrations
   */
  public List<Integration> getIntegrations() {
    return integrations;
  }

  /** Set integrations */
  public void setIntegrations(List<Integration> integrations) {
    this.integrations = integrations;
  }

  public AppStarted integrations(List<Integration> integrations) {
    this.integrations = integrations;
    return this;
  }

  public AppStarted addIntegrationsItem(Integration integrationsItem) {
    this.integrations.add(integrationsItem);
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppStarted {\n");
    sb.append("    ").append(super.toString()).append("\n");
    sb.append("    _configuration: ").append(configuration).append("\n");
    sb.append("    dependencies: ").append(dependencies).append("\n");
    sb.append("    integrations: ").append(integrations).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
