/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

public class Dependency {

  @com.squareup.moshi.Json(name = "hash")
  private String hash;

  @com.squareup.moshi.Json(name = "name")
  private String name;

  @com.squareup.moshi.Json(name = "type")
  private DependencyType type;

  @com.squareup.moshi.Json(name = "version")
  private String version;

  /**
   * Get hash
   *
   * @return hash
   */
  public String getHash() {
    return hash;
  }

  /** Set hash */
  public void setHash(String hash) {
    this.hash = hash;
  }

  public Dependency hash(String hash) {
    this.hash = hash;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  public String getName() {
    return name;
  }

  /** Set name */
  public void setName(String name) {
    this.name = name;
  }

  public Dependency name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get type
   *
   * @return type
   */
  public DependencyType getType() {
    return type;
  }

  /** Set type */
  public void setType(DependencyType type) {
    this.type = type;
  }

  public Dependency type(DependencyType type) {
    this.type = type;
    return this;
  }

  /**
   * Get version
   *
   * @return version
   */
  public String getVersion() {
    return version;
  }

  /** Set version */
  public void setVersion(String version) {
    this.version = version;
  }

  public Dependency version(String version) {
    this.version = version;
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dependency {\n");

    sb.append("    hash: ").append(hash).append("\n");
    sb.append("    name: ").append(name).append("\n");
    sb.append("    type: ").append(type).append("\n");
    sb.append("    version: ").append(version).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
