/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

/** Gets or Sets DependencyType */
public enum DependencyType {
  @com.squareup.moshi.Json(name = "SharedSystemLibrary")
  SHARED_SYSTEM_LIBRARY("SharedSystemLibrary"),

  @com.squareup.moshi.Json(name = "PlatformStandard")
  PLATFORM_STANDARD("PlatformStandard");

  private final String value;

  DependencyType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DependencyType fromValue(String text) {
    for (DependencyType b : DependencyType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}
