/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

import java.util.ArrayList;
import java.util.List;

public class GenerateMetrics extends Payload {

  @com.squareup.moshi.Json(name = "namespace")
  private String namespace;

  @com.squareup.moshi.Json(name = "series")
  private List<Metric> series = new ArrayList<Metric>();

  /**
   * Get namespace
   *
   * @return namespace
   */
  public String getNamespace() {
    return namespace;
  }

  /** Set namespace */
  public void setNamespace(String namespace) {
    this.namespace = namespace;
  }

  public GenerateMetrics namespace(String namespace) {
    this.namespace = namespace;
    return this;
  }

  /**
   * Get series
   *
   * @return series
   */
  public List<Metric> getSeries() {
    return series;
  }

  /** Set series */
  public void setSeries(List<Metric> series) {
    this.series = series;
  }

  public GenerateMetrics series(List<Metric> series) {
    this.series = series;
    return this;
  }

  public GenerateMetrics addSeriesItem(Metric seriesItem) {
    this.series.add(seriesItem);
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenerateMetrics {\n");
    sb.append("    ").append(super.toString()).append("\n");
    sb.append("    namespace: ").append(namespace).append("\n");
    sb.append("    series: ").append(series).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
