/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

public class Host {

  @com.squareup.moshi.Json(name = "architecture")
  private String architecture;

  @com.squareup.moshi.Json(name = "hostname")
  private String hostname;

  @com.squareup.moshi.Json(name = "kernel_name")
  private String kernelName;

  @com.squareup.moshi.Json(name = "kernel_release")
  private String kernelRelease;

  @com.squareup.moshi.Json(name = "kernel_version")
  private String kernelVersion;

  @com.squareup.moshi.Json(name = "os")
  private String os;

  @com.squareup.moshi.Json(name = "os_version")
  private String osVersion;

  /**
   * Get architecture
   *
   * @return architecture
   */
  public String getArchitecture() {
    return architecture;
  }

  /** Set architecture */
  public void setArchitecture(String architecture) {
    this.architecture = architecture;
  }

  public Host architecture(String architecture) {
    this.architecture = architecture;
    return this;
  }

  /**
   * Get hostname
   *
   * @return hostname
   */
  public String getHostname() {
    return hostname;
  }

  /** Set hostname */
  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public Host hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

  /**
   * Get kernelName
   *
   * @return kernelName
   */
  public String getKernelName() {
    return kernelName;
  }

  /** Set kernelName */
  public void setKernelName(String kernelName) {
    this.kernelName = kernelName;
  }

  public Host kernelName(String kernelName) {
    this.kernelName = kernelName;
    return this;
  }

  /**
   * Get kernelRelease
   *
   * @return kernelRelease
   */
  public String getKernelRelease() {
    return kernelRelease;
  }

  /** Set kernelRelease */
  public void setKernelRelease(String kernelRelease) {
    this.kernelRelease = kernelRelease;
  }

  public Host kernelRelease(String kernelRelease) {
    this.kernelRelease = kernelRelease;
    return this;
  }

  /**
   * Get kernelVersion
   *
   * @return kernelVersion
   */
  public String getKernelVersion() {
    return kernelVersion;
  }

  /** Set kernelVersion */
  public void setKernelVersion(String kernelVersion) {
    this.kernelVersion = kernelVersion;
  }

  public Host kernelVersion(String kernelVersion) {
    this.kernelVersion = kernelVersion;
    return this;
  }

  /**
   * Get os
   *
   * @return os
   */
  public String getOs() {
    return os;
  }

  /** Set os */
  public void setOs(String os) {
    this.os = os;
  }

  public Host os(String os) {
    this.os = os;
    return this;
  }

  /**
   * Get osVersion
   *
   * @return osVersion
   */
  public String getOsVersion() {
    return osVersion;
  }

  /** Set osVersion */
  public void setOsVersion(String osVersion) {
    this.osVersion = osVersion;
  }

  public Host osVersion(String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Host {\n");

    sb.append("    architecture: ").append(architecture).append("\n");
    sb.append("    hostname: ").append(hostname).append("\n");
    sb.append("    kernelName: ").append(kernelName).append("\n");
    sb.append("    kernelRelease: ").append(kernelRelease).append("\n");
    sb.append("    kernelVersion: ").append(kernelVersion).append("\n");
    sb.append("    os: ").append(os).append("\n");
    sb.append("    osVersion: ").append(osVersion).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
