/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

public class Integration {

  @com.squareup.moshi.Json(name = "auto_enabled")
  private Boolean autoEnabled;

  @com.squareup.moshi.Json(name = "compatible")
  private Boolean compatible;

  @com.squareup.moshi.Json(name = "enabled")
  private Boolean enabled;

  @com.squareup.moshi.Json(name = "name")
  private String name;

  @com.squareup.moshi.Json(name = "version")
  private String version;

  /**
   * Get autoEnabled
   *
   * @return autoEnabled
   */
  public Boolean getAutoEnabled() {
    return autoEnabled;
  }

  /** Set autoEnabled */
  public void setAutoEnabled(Boolean autoEnabled) {
    this.autoEnabled = autoEnabled;
  }

  public Integration autoEnabled(Boolean autoEnabled) {
    this.autoEnabled = autoEnabled;
    return this;
  }

  /**
   * Get compatible
   *
   * @return compatible
   */
  public Boolean getCompatible() {
    return compatible;
  }

  /** Set compatible */
  public void setCompatible(Boolean compatible) {
    this.compatible = compatible;
  }

  public Integration compatible(Boolean compatible) {
    this.compatible = compatible;
    return this;
  }

  /**
   * Get enabled
   *
   * @return enabled
   */
  public Boolean getEnabled() {
    return enabled;
  }

  /** Set enabled */
  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public Integration enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  public String getName() {
    return name;
  }

  /** Set name */
  public void setName(String name) {
    this.name = name;
  }

  public Integration name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get version
   *
   * @return version
   */
  public String getVersion() {
    return version;
  }

  /** Set version */
  public void setVersion(String version) {
    this.version = version;
  }

  public Integration version(String version) {
    this.version = version;
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Integration {\n");

    sb.append("    autoEnabled: ").append(autoEnabled).append("\n");
    sb.append("    compatible: ").append(compatible).append("\n");
    sb.append("    enabled: ").append(enabled).append("\n");
    sb.append("    name: ").append(name).append("\n");
    sb.append("    version: ").append(version).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
