/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

public class Payload {

  @com.squareup.moshi.Json(name = "request_type")
  private RequestType requestType;

  /**
   * Get requestType
   *
   * @return requestType
   */
  public RequestType getRequestType() {
    return requestType;
  }

  /** Set requestType */
  public void setRequestType(RequestType requestType) {
    this.requestType = requestType;
  }

  public Payload requestType(RequestType requestType) {
    this.requestType = requestType;
    return this;
  }

  /** Create a string representation of this pojo. */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Payload {\n");

    sb.append("    requestType: ").append(requestType).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
