/**
 * Datadog Telemetry API Generated by Openapi Generator
 * https://github.com/openapitools/openapi-generator
 *
 * <p>The version of the OpenAPI document: 1.0.0
 *
 * <p>NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 */
package datadog.telemetry.api;

/** Payload type variant */
public enum RequestType {
  @com.squareup.moshi.Json(name = "app-started")
  APP_STARTED("app-started"),

  @com.squareup.moshi.Json(name = "app-client-configuration-change")
  APP_CLIENT_CONFIGURATION_CHANGE("app-client-configuration-change"),

  @com.squareup.moshi.Json(name = "app-dependencies-loaded")
  APP_DEPENDENCIES_LOADED("app-dependencies-loaded"),

  @com.squareup.moshi.Json(name = "app-integrations-change")
  APP_INTEGRATIONS_CHANGE("app-integrations-change"),

  @com.squareup.moshi.Json(name = "app-heartbeat")
  APP_HEARTBEAT("app-heartbeat"),

  @com.squareup.moshi.Json(name = "app-closing")
  APP_CLOSING("app-closing"),

  @com.squareup.moshi.Json(name = "generate-metrics")
  GENERATE_METRICS("generate-metrics"),

  @com.squareup.moshi.Json(name = "logs")
  LOGS("logs"),

  @com.squareup.moshi.Json(name = "distributions")
  DISTRIBUTIONS("distributions");

  private final String value;

  RequestType(String value) {
    this.value = value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static RequestType fromValue(String text) {
    for (RequestType b : RequestType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + text + "'");
  }
}
