ddagent:
    image: datadog/docker-dd-agent
    environment:
        - STS_BIND_HOST=0.0.0.0
        - STS_API_KEY
    ports:
        - "127.0.0.1:8126:8126"
redis:
   image: redis
   ports:
        - "127.0.0.1:6379:6379"
