plugins {
  id 'idea'
  id 'dd-trace-java.module.instrumentation'
  // Use slf4j-simple as default; logback has a high chance of getting stuck in a deadlock on CI.
  id 'dd-trace-java.conventions.testing.slf4j-simple'
}

muzzle {
  pass {
    coreJdk('25')
  }
}

idea {
  module {
    jdkName = '25'
  }
}
