mongo:
    image: mongo:3.2
    ports:
        - "127.0.0.1:27017:27017"

ddagent:
    image: datadog/docker-dd-agent
    environment:
        - STS_BIND_HOST=0.0.0.0
        - STS_API_KEY
    ports:
        - "127.0.0.1:8126:8126"
