plugins {
  id 'dd-trace-java.module.instrumentation'
  id 'dd-trace-java.call-site-instrumentation'
}

testJvmConstraints {
  minJavaVersion = JavaVersion.VERSION_11
}

muzzle {
  pass {
    coreJdk()
  }
}

csi {
  javaVersion = JavaLanguageVersion.of(11)
}

addTestSuiteForDir('latestDepTest', 'test')

dependencies {
  testRuntimeOnly project(':dd-java-agent:instrumentation:datadog:asm:iast-instrumenter')
}

project.tasks.withType(AbstractCompile).configureEach {
  switch (it.name) {
    case 'compileCsiJava':
      break
    default:
      configureCompiler(it, JavaVersion.VERSION_11)
  }
}
