package com.datadog.appsec.sca;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.StringReader;
import java.util.List;
import org.junit.jupiter.api.Test;

class ScaCveDatabaseTest {

  private static final String MINIMAL_JSON =
      "{\"version\":1,\"entries\":["
          + "{\"vuln_id\":\"GHSA-test-1234-5678\","
          + "\"artifact\":\"com.example:lib\","
          + "\"version_ranges\":[\"< 2.0.0\"],"
          + "\"symbols\":["
          + "{\"class\":\"com/example/Foo\",\"method\":null},"
          + "{\"class\":\"com/example/Bar\",\"method\":null}"
          + "]}]}";

  @Test
  void loadsFromJson() throws Exception {
    ScaCveDatabase db = ScaCveDatabase.parse(new StringReader(MINIMAL_JSON));

    assertFalse(db.isEmpty());
    assertEquals(2, db.size()); // 2 unique class names
  }

  @Test
  void indexedByClassName() throws Exception {
    ScaCveDatabase db = ScaCveDatabase.parse(new StringReader(MINIMAL_JSON));

    List<ScaEntry> entries = db.entriesForClass("com/example/Foo");
    assertNotNull(entries);
    assertEquals(1, entries.size());
    assertEquals("GHSA-test-1234-5678", entries.get(0).vulnId());
    assertEquals("com.example:lib", entries.get(0).artifact());
  }

  @Test
  void unknownClassReturnsNull() throws Exception {
    ScaCveDatabase db = ScaCveDatabase.parse(new StringReader(MINIMAL_JSON));

    assertNull(db.entriesForClass("com/example/Unknown"));
  }

  @Test
  void emptyEntriesProducesEmptyDatabase() throws Exception {
    String json = "{\"version\":1,\"entries\":[]}";
    ScaCveDatabase db = ScaCveDatabase.parse(new StringReader(json));

    assertTrue(db.isEmpty());
  }

  @Test
  void malformedEntryIsSkipped() throws Exception {
    String json =
        "{\"version\":1,\"entries\":["
            + "{\"vuln_id\":null,\"artifact\":\"com.example:lib\","
            + "\"version_ranges\":[\"< 2.0.0\"],\"symbols\":[{\"class\":\"com/example/Foo\",\"method\":null}]},"
            + "{\"vuln_id\":\"GHSA-good-0000-0000\",\"artifact\":\"com.example:other\","
            + "\"version_ranges\":[\"< 1.0.0\"],\"symbols\":[{\"class\":\"com/example/Good\",\"method\":null}]}"
            + "]}";

    ScaCveDatabase db = ScaCveDatabase.parse(new StringReader(json));

    assertNull(db.entriesForClass("com/example/Foo"));
    assertNotNull(db.entriesForClass("com/example/Good"));
  }

  @Test
  void multipleEntriesForSameClass() throws Exception {
    String json =
        "{\"version\":1,\"entries\":["
            + "{\"vuln_id\":\"GHSA-aaaa-0001-0001\",\"artifact\":\"com.example:lib\","
            + "\"version_ranges\":[\"< 2.0.0\"],\"symbols\":[{\"class\":\"com/example/Shared\",\"method\":null}]},"
            + "{\"vuln_id\":\"GHSA-bbbb-0002-0002\",\"artifact\":\"com.example:lib\","
            + "\"version_ranges\":[\"< 3.0.0\"],\"symbols\":[{\"class\":\"com/example/Shared\",\"method\":null}]}"
            + "]}";

    ScaCveDatabase db = ScaCveDatabase.parse(new StringReader(json));

    List<ScaEntry> entries = db.entriesForClass("com/example/Shared");
    assertNotNull(entries);
    assertEquals(2, entries.size());
  }

  @Test
  void loadFromClasspathSucceeds() {
    // Verifies the real sca_cves.json generated by generateScaCvesJson is valid and loadable
    ScaCveDatabase db = ScaCveDatabase.load();

    assertFalse(db.isEmpty(), "sca_cves.json should be on the classpath and contain entries");
    assertTrue(db.size() > 0);
  }

  @Test
  void jacksonDatabindObjectMapperIsIndexed() {
    // Spot-check a known entry from the real database
    ScaCveDatabase db = ScaCveDatabase.load();

    List<ScaEntry> entries = db.entriesForClass("com/fasterxml/jackson/databind/ObjectMapper");
    assertNotNull(entries, "jackson-databind ObjectMapper should be in the database");
    assertFalse(entries.isEmpty());
  }
}
