package datadog.trace.instrumentation.java.lang.invoke;

import com.google.auto.service.AutoService;
import datadog.trace.agent.tooling.Instrumenter;
import datadog.trace.agent.tooling.InstrumenterModule;
import datadog.trace.agent.tooling.JavaModuleOpenProvider;
import datadog.trace.bootstrap.instrumentation.java.lang.invoke.LambdaTransformerHelper;
import java.util.Collection;
import java.util.Collections;
import net.bytebuddy.asm.AsmVisitorWrapper;
import net.bytebuddy.description.field.FieldDescription;
import net.bytebuddy.description.field.FieldList;
import net.bytebuddy.description.method.MethodList;
import net.bytebuddy.description.type.TypeDefinition;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.implementation.Implementation;
import net.bytebuddy.jar.asm.ClassVisitor;
import net.bytebuddy.jar.asm.ClassWriter;
import net.bytebuddy.jar.asm.MethodVisitor;
import net.bytebuddy.jar.asm.Opcodes;
import net.bytebuddy.jar.asm.Type;
import net.bytebuddy.matcher.ElementMatcher;
import net.bytebuddy.pool.TypePool;
import net.bytebuddy.utility.OpenedClassReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Instruments {@code java.lang.invoke.InnerClassLambdaMetafactory} so that generated lambda classes
 * are routed through the agent's class-file transformer before they are defined. This lets lambda
 * {@code Runnable}/{@code Callable} tasks receive field-backed context-store injection (and the
 * matching advice) just like ordinary classes, instead of being wrapped.
 *
 * <p>The generated bytes come from {@code ClassWriter.toByteArray()} on JDK 8-21 and {@code
 * ClassFile.build(...)} on JDK 25-27, one call site per JDK; the switch happened between 21 and 25,
 * and 22-24 were not checked. We use an ASM visitor — rather than {@code @Advice} — because the
 * transform call must be inserted in the middle of {@code spinInnerClass}/{@code
 * generateInnerClass}, right after that call.
 */
@AutoService(InstrumenterModule.class)
public final class LambdaMetafactoryInstrumentation extends InstrumenterModule.ContextTracking
    implements Instrumenter.ForBootstrap,
        Instrumenter.ForSingleType,
        Instrumenter.HasTypeAdvice,
        Instrumenter.WithTypeStructure,
        JavaModuleOpenProvider {

  private static final Logger log = LoggerFactory.getLogger(LambdaMetafactoryInstrumentation.class);

  private static final String METAFACTORY = "java.lang.invoke.InnerClassLambdaMetafactory";

  private static final String LAMBDA_CLASS_NAME_FIELD = "lambdaClassName";
  private static final String TARGET_CLASS_FIELD = "targetClass";
  private static final String INTERFACE_CLASS_FIELD = "interfaceClass";

  public LambdaMetafactoryInstrumentation() {
    super("lambda");
  }

  @Override
  protected boolean defaultEnabled() {
    // Opt-in for the first iteration: enable with DD_TRACE_LAMBDA_ENABLED=true.
    return false;
  }

  @Override
  public String instrumentedType() {
    return METAFACTORY;
  }

  @Override
  public Collection<String> triggerClasses() {
    return Collections.singleton(METAFACTORY);
  }

  /**
   * The injected bytecode reads {@code lambdaClassName}, {@code targetClass}, and {@code
   * interfaceClass} directly. If a JDK renames or drops any of them, the resulting {@code
   * NoSuchFieldError} would break every lambda linkage in the JVM, so the type is only transformed
   * when all three resolve. The class fields are declared across the hierarchy, hence the hierarchy
   * walk.
   */
  @Override
  public ElementMatcher<TypeDescription> structureMatcher() {
    return HasMetafactoryFields.INSTANCE;
  }

  /**
   * Public because the agent loads {@code *Instrumentation} classes in a child class-loader of the
   * one that loads this nested class; package-private access across the two is denied.
   */
  public static final class HasMetafactoryFields implements ElementMatcher<TypeDescription> {
    public static final HasMetafactoryFields INSTANCE = new HasMetafactoryFields();

    @Override
    public boolean matches(TypeDescription target) {
      return declaresField(target, LAMBDA_CLASS_NAME_FIELD, String.class.getName())
          && declaresField(target, TARGET_CLASS_FIELD, Class.class.getName())
          && declaresField(target, INTERFACE_CLASS_FIELD, Class.class.getName());
    }

    private static boolean declaresField(TypeDescription type, String name, String fieldType) {
      for (TypeDefinition current = type; current != null; current = current.getSuperClass()) {
        for (FieldDescription field : current.asErasure().getDeclaredFields()) {
          if (name.equals(field.getName())
              && fieldType.equals(field.getType().asErasure().getName())) {
            return true;
          }
        }
      }
      return false;
    }
  }

  @Override
  public void typeAdvice(TypeTransformer transformer) {
    transformer.applyAdvice(new MetafactoryVisitorWrapper());
  }

  public static final class MetafactoryVisitorWrapper implements AsmVisitorWrapper {
    @Override
    public int mergeWriter(int flags) {
      return flags | ClassWriter.COMPUTE_MAXS;
    }

    @Override
    public int mergeReader(int flags) {
      return flags;
    }

    @Override
    public ClassVisitor wrap(
        TypeDescription instrumentedType,
        ClassVisitor classVisitor,
        Implementation.Context implementationContext,
        TypePool typePool,
        FieldList<FieldDescription.InDefinedShape> fields,
        MethodList<?> methods,
        int writerFlags,
        int readerFlags) {
      return new MetafactoryClassVisitor(classVisitor, instrumentedType.getInternalName());
    }
  }

  private static final class MetafactoryClassVisitor extends ClassVisitor {
    private final String slashClassName;
    private boolean injected;

    MetafactoryClassVisitor(ClassVisitor cv, String slashClassName) {
      super(OpenedClassReader.ASM_API, cv);
      this.slashClassName = slashClassName;
    }

    @Override
    public MethodVisitor visitMethod(
        int access, String name, String descriptor, String signature, String[] exceptions) {
      MethodVisitor mv = super.visitMethod(access, name, descriptor, signature, exceptions);
      // Up to JDK 21 the bytes are produced in spinInnerClass; from 25 spinInnerClass delegates
      // to generateInnerClass, which produces them.
      if (("spinInnerClass".equals(name) || "generateInnerClass".equals(name))
          && "()Ljava/lang/Class;".equals(descriptor)) {
        return new MetafactoryMethodVisitor(api, mv, slashClassName, this);
      }
      return mv;
    }

    @Override
    public void visitEnd() {
      super.visitEnd();
      if (!injected) {
        // The fields resolved but the generated bytes are no longer produced where we expect, so
        // no lambda will be field-injected and every task falls back to wrapping.
        log.debug(
            "No injection site found in {}; lambda field-injection is inactive.", slashClassName);
      }
    }
  }

  private static final class MetafactoryMethodVisitor extends MethodVisitor {
    private final String slashClassName;
    private final MetafactoryClassVisitor declaringVisitor;

    MetafactoryMethodVisitor(
        int api,
        MethodVisitor mv,
        String slashClassName,
        MetafactoryClassVisitor declaringVisitor) {
      super(api, mv);
      this.slashClassName = slashClassName;
      this.declaringVisitor = declaringVisitor;
    }

    @Override
    public void visitMethodInsn(
        int opcode, String owner, String name, String descriptor, boolean isInterface) {
      super.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
      // After the generated bytes are produced, insert a call to our transformer. The byte[] is
      // on the stack. Owners are matched loosely so a repackaging only costs the feature, while
      // still ruling out unrelated calls such as ByteArrayOutputStream.toByteArray().
      if ((opcode == Opcodes.INVOKEVIRTUAL
              && "toByteArray".equals(name)
              && "()[B".equals(descriptor)
              && owner.endsWith("/ClassWriter"))
          || (opcode == Opcodes.INVOKEINTERFACE
              && "build".equals(name)
              && descriptor.endsWith(")[B")
              && owner.endsWith("/ClassFile"))) {
        // stack: ..., byte[]
        super.visitVarInsn(Opcodes.ALOAD, 0);
        super.visitFieldInsn(
            Opcodes.GETFIELD, slashClassName, LAMBDA_CLASS_NAME_FIELD, "Ljava/lang/String;");
        super.visitVarInsn(Opcodes.ALOAD, 0);
        // targetClass yields the ClassLoader where the lambda class will be defined.
        super.visitFieldInsn(
            Opcodes.GETFIELD, slashClassName, TARGET_CLASS_FIELD, "Ljava/lang/Class;");
        super.visitVarInsn(Opcodes.ALOAD, 0);
        // interfaceClass lets the helper cheaply reject non-Runnable lambdas before matching.
        super.visitFieldInsn(
            Opcodes.GETFIELD, slashClassName, INTERFACE_CLASS_FIELD, "Ljava/lang/Class;");
        super.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            Type.getInternalName(LambdaTransformerHelper.class),
            "transform",
            "([BLjava/lang/String;Ljava/lang/Class;Ljava/lang/Class;)[B",
            false);
        // stack: ..., byte[] (transformed)
        declaringVisitor.injected = true;
      }
    }
  }
}
