package datadog.trace.instrumentation.java.lang.invoke;

import com.google.auto.service.AutoService;
import datadog.trace.agent.tooling.Instrumenter;
import datadog.trace.agent.tooling.InstrumenterModule;
import datadog.trace.agent.tooling.JavaModuleOpenProvider;
import datadog.trace.bootstrap.instrumentation.java.lang.invoke.LambdaTransformerHelper;
import java.util.Collection;
import java.util.Collections;
import net.bytebuddy.asm.AsmVisitorWrapper;
import net.bytebuddy.description.field.FieldDescription;
import net.bytebuddy.description.field.FieldList;
import net.bytebuddy.description.method.MethodList;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.implementation.Implementation;
import net.bytebuddy.jar.asm.ClassVisitor;
import net.bytebuddy.jar.asm.ClassWriter;
import net.bytebuddy.jar.asm.MethodVisitor;
import net.bytebuddy.jar.asm.Opcodes;
import net.bytebuddy.jar.asm.Type;
import net.bytebuddy.pool.TypePool;

/**
 * Instruments {@code java.lang.invoke.InnerClassLambdaMetafactory} so that generated lambda classes
 * are routed through the agent's class-file transformer before they are defined. This lets lambda
 * {@code Runnable}/{@code Callable} tasks receive field-backed context-store injection (and the
 * matching advice) just like ordinary classes, instead of being wrapped.
 *
 * <p>The generated bytecode is finalized by a call to ASM's {@code ClassWriter.toByteArray()} (or
 * the class-file API {@code build()} on JDK 24). We use an ASM visitor — rather than
 * {@code @Advice} — because the transform call must be inserted in the middle of {@code
 * spinInnerClass}/{@code generateInnerClass}, right after that call. This mirrors the approach used
 * by OpenTelemetry's {@code internal-lambda} instrumentation.
 */
@AutoService(InstrumenterModule.class)
public final class LambdaMetafactoryInstrumentation extends InstrumenterModule.ContextTracking
    implements Instrumenter.ForBootstrap,
        Instrumenter.ForSingleType,
        Instrumenter.HasTypeAdvice,
        JavaModuleOpenProvider {

  private static final String METAFACTORY = "java.lang.invoke.InnerClassLambdaMetafactory";

  public LambdaMetafactoryInstrumentation() {
    super("lambda");
  }

  @Override
  protected boolean defaultEnabled() {
    // Opt-in for the first iteration: enable with DD_TRACE_LAMBDA_ENABLED=true.
    return false;
  }

  @Override
  public String instrumentedType() {
    return METAFACTORY;
  }

  @Override
  public Collection<String> triggerClasses() {
    return Collections.singleton(METAFACTORY);
  }

  @Override
  public void typeAdvice(TypeTransformer transformer) {
    transformer.applyAdvice(new MetafactoryVisitorWrapper());
  }

  public static final class MetafactoryVisitorWrapper implements AsmVisitorWrapper {
    @Override
    public int mergeWriter(int flags) {
      return flags | ClassWriter.COMPUTE_MAXS;
    }

    @Override
    public int mergeReader(int flags) {
      return flags;
    }

    @Override
    public ClassVisitor wrap(
        TypeDescription instrumentedType,
        ClassVisitor classVisitor,
        Implementation.Context implementationContext,
        TypePool typePool,
        FieldList<FieldDescription.InDefinedShape> fields,
        MethodList<?> methods,
        int writerFlags,
        int readerFlags) {
      return new MetafactoryClassVisitor(classVisitor, instrumentedType.getInternalName());
    }
  }

  private static final class MetafactoryClassVisitor extends ClassVisitor {
    private final String slashClassName;

    MetafactoryClassVisitor(ClassVisitor cv, String slashClassName) {
      super(Opcodes.ASM7, cv);
      this.slashClassName = slashClassName;
    }

    @Override
    public MethodVisitor visitMethod(
        int access, String name, String descriptor, String signature, String[] exceptions) {
      MethodVisitor mv = super.visitMethod(access, name, descriptor, signature, exceptions);
      // Depending on the JDK version the lambda class is spun in spinInnerClass or
      // generateInnerClass, both returning the generated Class.
      if (("spinInnerClass".equals(name) || "generateInnerClass".equals(name))
          && "()Ljava/lang/Class;".equals(descriptor)) {
        return new MetafactoryMethodVisitor(api, mv, slashClassName);
      }
      return mv;
    }
  }

  private static final class MetafactoryMethodVisitor extends MethodVisitor {
    private final String slashClassName;

    MetafactoryMethodVisitor(int api, MethodVisitor mv, String slashClassName) {
      super(api, mv);
      this.slashClassName = slashClassName;
    }

    @Override
    public void visitMethodInsn(
        int opcode, String owner, String name, String descriptor, boolean isInterface) {
      super.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
      // After the generated bytes are produced (ClassWriter.toByteArray() or, on JDK 24, the
      // class-file API build()), insert a call to our transformer. The byte[] is on the stack.
      if ((opcode == Opcodes.INVOKEVIRTUAL
              && "toByteArray".equals(name)
              && "()[B".equals(descriptor))
          || (opcode == Opcodes.INVOKEINTERFACE
              && "build".equals(name)
              && descriptor.endsWith(")[B"))) {
        // stack: ..., byte[]
        super.visitVarInsn(Opcodes.ALOAD, 0);
        super.visitFieldInsn(
            Opcodes.GETFIELD, slashClassName, "lambdaClassName", "Ljava/lang/String;");
        super.visitVarInsn(Opcodes.ALOAD, 0);
        // targetClass yields the ClassLoader where the lambda class will be defined.
        super.visitFieldInsn(Opcodes.GETFIELD, slashClassName, "targetClass", "Ljava/lang/Class;");
        super.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            Type.getInternalName(LambdaTransformerHelper.class),
            "transform",
            "([BLjava/lang/String;Ljava/lang/Class;)[B",
            false);
        // stack: ..., byte[] (transformed)
      }
    }
  }
}
