package datadog.trace.core.datastreams;

import datadog.trace.api.DataStreamsCheckpointer;

public class DefaultDataStreamsCheckpointer implements DataStreamsCheckpointer {
  @Override
  public void setDataStreamCheckpoint(String edgeName) {
    // TODO Autogenerated method stub

  }
}
