plugins {
  id 'dd-trace-java.module.instrumentation'
}

muzzle {
  pass {
    group = "org.eclipse.jetty"
    module = "jetty-client"
    versions = "[12,)"
    javaVersion = "17"
    assertInverse = true
  }
  pass {
    group = "org.eclipse.jetty.websocket"
    module = "jetty-websocket-core-client"
    versions = "[12,)"
    javaVersion = "17"
  }
}

tracerJava {
  addSourceSetFor(JavaVersion.VERSION_17)
}

addTestSuiteForDir('latestDepTest', 'test')

configurations.matching { it.name.startsWith('test') || it.name.startsWith('latestDepTest') }.configureEach {
  it.resolutionStrategy {
    force group: 'org.slf4j', name: 'slf4j-api', version: libs.versions.slf4j.get()
  }
}

dependencies {
  main_java17CompileOnly group: 'org.eclipse.jetty', name: 'jetty-client', version: '12.0.0'
  main_java17CompileOnly group: 'org.eclipse.jetty.websocket', name: 'jetty-websocket-core-client', version: '12.0.0'
  // to test conflicts
  testImplementation(project(':dd-java-agent:instrumentation:jetty:jetty-client:jetty-client-9.1'))
  testImplementation(project(':dd-java-agent:instrumentation:jetty:jetty-client:jetty-client-10.0'))

  testImplementation(project(path:':dd-java-agent:testing', 'configuration': 'shadow')) {
    // explicitly declared below.
    exclude group: 'org.eclipse.jetty'
  }
  testImplementation project(':dd-java-agent:instrumentation:jetty:jetty-util-9.4.31')
  testImplementation group: 'org.eclipse.jetty', name: 'jetty-client', version: '12.0.0'
  testImplementation 'org.eclipse.jetty.websocket:jetty-websocket-jetty-client:12.0.0'
  testImplementation 'org.eclipse.jetty.websocket:jetty-websocket-jetty-server:12.0.0'
  testImplementation libs.bundles.mockito
  testRuntimeOnly project(':dd-java-agent:instrumentation:jetty:jetty-server:jetty-server-12.0')
  latestDepTestImplementation group: 'org.eclipse.jetty', name: 'jetty-client', version: '12.+'
  latestDepTestImplementation 'org.eclipse.jetty.websocket:jetty-websocket-jetty-client:12.+'
  latestDepTestImplementation 'org.eclipse.jetty.websocket:jetty-websocket-jetty-server:12.+'
}
