FROM debian:bookworm-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y procps tini build-essential git curl unzip zip && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

# install sdkman
COPY .sdkmanrc .
RUN curl -s "https://get.sdkman.io" | bash
RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && \
    sdk env install && \
    sdk flush"

RUN mkdir exploration-tests
WORKDIR /exploration-tests
# jsoup
RUN git clone -b jsoup-1.18.1 https://github.com/jhy/jsoup.git
COPY jsoup_exploration-tests.patch .
# fix tests that are failing because checking time to execute
RUN cd jsoup && git apply /exploration-tests/jsoup_exploration-tests.patch
RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && cd jsoup && mvn verify -DskipTests=true"


# Jackson
RUN git clone -b 2.16 https://github.com/FasterXML/jackson-core.git
COPY jackson-core_exploration-tests.patch .
# fix tests that are failing because timeout
RUN cd jackson-core && git apply /exploration-tests/jackson-core_exploration-tests.patch
RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && cd jackson-core && mvn verify -DskipTests=true"
RUN git clone -b 2.16 https://github.com/FasterXML/jackson-databind.git
COPY jackson-databind_exploration-tests.patch .
# fix tests that are failing because too deep recrursion
RUN cd jackson-databind && git apply /exploration-tests/jackson-databind_exploration-tests.patch
RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && cd jackson-databind && mvn verify -DskipTests=true"

# Netty
#RUN git clone https://github.com/netty/netty.git
#RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && cd netty && ./mvnw dependency:resolve dependency:resolve-plugins"

# Guava
#RUN git clone https://github.com/google/guava.git
#RUN bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && cd guava && mvn -B -P!standard-with-extra-repos verify -U -Dmaven.javadoc.skip=true -DskipTests=true"

