issuer: https://gitlab.ddbuild.io

# DEBUG: ref should be "master"
subject: "project_path:DataDog/apm-reliability/dd-trace-java:ref_type:branch:ref:sarahchen6/use-octo-sts"

claim_pattern:
  project_path: "DataDog/apm-reliability/dd-trace-java"
  ref_type: "branch"
  # ref: "master"

permissions:
  contents: "write"
