issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/dd-trace-java:ref:refs/heads/master

claim_pattern:
  event_name: release
  ref: refs/heads/master
  ref_protected: "true"
  job_workflow_ref: DataDog/dd-trace-java/\.github/workflows/add-release-to-cloudfoundry\.yaml@refs/heads/master

permissions:
  contents: write
