issuer: https://token.actions.githubusercontent.com

subject_pattern: repo:DataDog/dd-trace-java:ref:refs/heads/**

claim_pattern:
  event_name: (push|workflow_dispatch)
  ref: refs/heads/.+
  job_workflow_ref: DataDog/dd-trace-java/\.github/workflows/pin-system-tests\.yaml@refs/heads/master

permissions:
  contents: write
  pull_requests: write
