issuer: https://token.actions.githubusercontent.com

subject_pattern: repo:DataDog/dd-trace-java:ref:refs/(heads/master|tags/v[0-9]+.[0-9]+.0)

claim_pattern:
  event_name: (push|workflow_dispatch)
  ref: refs/(heads/master|tags/v[0-9]+\.[0-9]+\.0)
  job_workflow_ref: DataDog/dd-trace-java/\.github/workflows/create-release-branch\.yaml@refs/(heads/master|tags/v[0-9]+\.[0-9]+\.0)

permissions:
  contents: write
  pull_requests: write
