issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/dd-trace-java:ref:refs/heads/master

claim_pattern:
  event_name: enqueued
  job_workflow_ref: DataDog/dd-trace-java/.github/workflows/enforce-datadog-merge-queue.yaml@refs/heads/master

permissions:
  issues: write
  pull_requests: write
