package datadog.trace.api.interceptor;

import java.util.Map;

public interface MutableSpan<SPAN extends MutableSpan<SPAN>> {

  /** @return Start time with nanosecond scale, but millisecond resolution. */
  long getStartTime();

  /** @return Duration with nanosecond scale. */
  long getDurationNano();

  CharSequence getOperationName();

  SPAN setOperationName(final CharSequence serviceName);

  String getServiceName();

  SPAN setServiceName(final String serviceName);

  CharSequence getResourceName();

  SPAN setResourceName(final CharSequence resourceName);

  Integer getSamplingPriority();

  /**
   * @param newPriority
   * @return
   * @deprecated Use {@link io.opentracing.Span#setTag(String, boolean)} instead using either tag
   *     names {@link datadog.trace.api.DDTags#MANUAL_KEEP} or {@link
   *     datadog.trace.api.DDTags#MANUAL_DROP}.
   */
  @Deprecated
  SPAN setSamplingPriority(final int newPriority);

  String getSpanType();

  SPAN setSpanType(final CharSequence type);

  Map<String, Object> getTags();

  SPAN setTag(final String tag, final String value);

  SPAN setTag(final String tag, final boolean value);

  SPAN setTag(final String tag, final Number value);

  SPAN setMetric(final CharSequence metric, final int value);

  SPAN setMetric(final CharSequence metric, final long value);

  SPAN setMetric(final CharSequence metric, final double value);

  Boolean isError();

  SPAN setError(boolean value);

  /** @deprecated Use {@link #getLocalRootSpan()} instead. */
  @Deprecated
  SPAN getRootSpan();

  /**
   * Returns the root span for current the trace fragment. In the context of distributed tracing
   * this method returns the root span only for the fragment generated by the currently traced
   * application.
   *
   * @return The root span for the current trace fragment.
   */
  SPAN getLocalRootSpan();
}
