name: Create next milestone
on:
  milestone:
    types: [closed]

jobs:
  create_next_milestone:
    permissions:
      issues: write # Required to create a milestone
    runs-on: ubuntu-latest
    steps:
      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@18aa9ed4152808ab99b88d71f5481e41f8d89930 # 1.2.1
        with:
          version: ${{ github.event.milestone.title }}
      - name: Create next milestone
        uses: WyriHaximus/github-action-create-milestone@bb0276ee386c630b476fa3ca788457bf3daa7c2e # 1.1.1
        with:
          title: ${{ steps.semvers.outputs.minor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
