name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "Gradle wrapper validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
      # When updating this, you need to ADD the new version to https://github.com/DataDog/dd-trace-java/settings/actions
      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b # 1.0.4
