name: System Tests

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch: {}
  schedule:
    - cron:  '00 04 * * 2-6'

jobs:
  system-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lib-injection-enabled: ['lib-injection-enabled']
        lib-injection-connection: ['network', 'uds']
        lib-injection-use-admission-controller: ['', 'use-admission-controller']
    env:
      TEST_LIBRARY: java
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      LIBRARY_INJECTION_ENABLED: ${{ matrix.lib-injection-enabled }}
      LIBRARY_INJECTION_CONNECTION: ${{ matrix.lib-injection-connection }}
      LIBRARY_INJECTION_ADMISSION_CONTROLLER: ${{ matrix.lib-injection-admission-controller }}
      LIBRARY_INJECTION_INIT_IMAGE: ghcr.io/datadog/dd-trace-java/dd-lib-java-init:34db2f76715dbbe9168806bac7c89c7ad4d51996
      LIBRARY_INJECTION_TEST_APP_IMAGE: ghcr.io/datadog/dd-trace-java/dd-lib-java-init-test-app:34db2f76715dbbe9168806bac7c89c7ad4d51996

    steps:
      - name: Checkout system tests
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          repository: 'DataDog/system-tests'
          ref: 'injection-tests'  # TODO: update when https://github.com/DataDog/system-tests/pull/453 merged

      - name: Checkout dd-trace-js
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          path: 'binaries/dd-trace-java'

      - name: Build
        run: ./build.sh

      - name: Run
        run: ./run.sh

      - name: Compress artifact
        if: ${{ always() }}
        run: tar -czvf artifact.tar.gz $(ls | grep logs) || true

      - name: Upload artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
        if: ${{ always() }}
        with:
          name: logs
          path: artifact.tar.gz
