name: system-tests

on:
  pull_request:
  workflow_dispatch:

# Cancel long-running jobs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          submodules: 'recursive'

      - name: Cache Gradle dependencies
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4.2.2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
        
      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # v3.28.10
      #   with:
      #     languages: 'java'
      #     build-mode: 'manual'
      
      - name: Build dd-trace-java for creating the CodeQL database
        run: |
          GRADLE_OPTS="-Dorg.gradle.jvmargs='-Xmx2G -Xms2G'" \
          JAVA_HOME=$JAVA_HOME_8_X64 \
          JAVA_8_HOME=$JAVA_HOME_8_X64 \
          JAVA_11_HOME=$JAVA_HOME_11_X64 \
          JAVA_17_HOME=$JAVA_HOME_17_X64 \
          JAVA_21_HOME=$JAVA_HOME_21_X64 \
          ./gradlew clean :dd-java-agent:shadowJar \
            --build-cache --parallel --stacktrace --no-daemon --max-workers=4

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: workspace/dd-java-agent/build/libs/

  main:
    needs:
    - build
    uses:  DataDog/system-tests/.github/workflows/system-tests.yml@main
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      scenarios_groups: tracer-release
      library: java
      binaries_artifact: binaries
      skip_empty_scenarios: true
      desired_execution_time: 300  # 5 minutes
