name: "Lib Injection Test"

on: push

jobs:
  lib-injection-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      - name: Log in to the Container registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # 2.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # 2.0.0
        with:
          install: true
          config-inline: |
            [worker.oci]
              max-parallelism = 1

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@d08cf6ff1575077dee99962540d77ce91c62387d # 1.3.0
        with:
          config: lib-injection/kind-config.yaml
          cluster_name: lib-injection-testing
          kubectl_version: v1.22.10
          node_image: kindest/node:v1.22.9

      - name: Deploy apm test trace agent
        run: |
          kubectl apply -f lib-injection/dd-apm-test-agent-config.yaml
          kubectl rollout status daemonset/datadog-agent
          kubectl wait $(kubectl get pods -l app=datadog-agent -o name) --for condition=ready
          sleep 5

      - name: Build dd-java-agent.jar
        run: JAVA_HOME=$JAVA_HOME_8_X64 JAVA_11_HOME=$JAVA_HOME_11_X64 ./gradlew clean shadowJar --build-cache --parallel --no-daemon --max-workers=8

      - name: Build injection image
        run: |
          export BUILDX_PLATFORMS=`docker buildx imagetools inspect --raw busybox:latest | jq -r 'reduce (.manifests[] | [ .platform.os, .platform.architecture, .platform.variant ] | join("/") | sub("\\/$"; "")) as $item (""; . + "," + $item)' | sed 's/,//'`
          ./lib-injection/build.sh ghcr.io/datadog/dd-trace-java/dd-java-agent-k8s-init ${GITHUB_SHA}

      - name: Deploy pre-modified pod
        run: |
          kubectl apply -f lib-injection/app-config.yaml
          kubectl wait pod/my-app --for condition=ready
          sleep 5

      - name: Test
        run: |
          wget http://localhost:18126/test/traces
          TRACES=`cat traces`
          if [[ ${#TRACES} -lt 3 ]] ; then
            echo "No traces reported - ${TRACES}"
            exit 1
          else
            exit 0
          fi
