name: "Lib Injection Test"

on: push

jobs:
  lib-injection-test:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000
    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # 2.0.0

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@d08cf6ff1575077dee99962540d77ce91c62387d # 1.3.0
        with:
          config: lib-injection/kind-config.yaml
          cluster_name: lib-injection-testing
          kubectl_version: v1.22.10
          node_image: kindest/node:v1.22.9

      - name: Finish initializing kind+k8s for docker registry service
        run: |
          docker network connect "kind" "$(docker container ls --filter "ancestor=registry:2" --quiet)"
          kubectl apply -f lib-injection/local-registry-config.yaml

      - name: Deploy apm test trace agent
        run: |
          kubectl apply -f lib-injection/dd-apm-test-agent-config.yaml
          kubectl rollout status daemonset/datadog-agent
          kubectl wait $(kubectl get pods -l app=datadog-agent -o name) --for condition=ready
          sleep 5
          curl http://localhost:8126/test/traces

#      - name: Build dd-java-agent.jar
#        run: JAVA_HOME=$JAVA_HOME_8_X64 JAVA_11_HOME=$JAVA_HOME_11_X64 ./gradlew clean shadowJar --build-cache --parallel --no-daemon --max-workers=8

      - name: Build injection image
        run: |
          mkdir -p workspace/dd-java-agent/build/libs
          wget -O workspace/dd-java-agent/build/libs/dd-java-agent-latest.jar https://dtdg.co/latest-java-tracer
          ./lib-injection/build.sh "localhost:5001/dd-java-agent-init" "${GITHUB_SHA}"

      - name: Deploy pre-modified pod
        run: |
          kubectl apply -f lib-injection/app-config.yaml
          kubectl wait pod/my-app --for condition=ready --timeout=2m --v=1 || kubectl get pods
          kubectl describe pod my-app
          sleep 5
          curl http://localhost:8080/api
