name: Update System Tests

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  workflow_dispatch:
    inputs:
      ref:
        description: Reference to be updated (commit hash, branch, or tag)
        required: false
        type: string
      dry-run:
        description: Skip PR creation and only show changes
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  update-system-tests:
    name: "Update System Tests"
    runs-on: ubuntu-24.04
    steps:
      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/dd-trace-java
          policy: self.update-system-tests.create-pr

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0

      - name: Checkout System Test
        id: system-test-ref
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          repository: "DataDog/system-tests"
          path: system-tests
          ref: ${{ github.event.inputs.ref || '' }}

      - run: .github/scripts/update_reference.sh
        env:
          TARGET: ".github/workflows/run-system-tests.yaml"
          PATTERN: '(\s*system-tests.yml@)(\S+)(\s+# Automated:.*)'
          REF: ${{ steps.system-test-ref.outputs.commit }}

      - run: .github/scripts/update_reference.sh
        env:
          TARGET: ".github/workflows/run-system-tests.yaml"
          PATTERN: '(\s*ref: )(\S+)(\s+# Automated:.*)'
          REF: ${{ steps.system-test-ref.outputs.commit }}

      - run: git diff --color=always

      - name: Check if changes should be committed
        id: check-changes
        run: |
          if [[ -z "$(git status -s)" ]]; then
            echo "No changes to commit, exiting."
            echo "commit_changes=false" >> "$GITHUB_OUTPUT"
            exit 0
          else
            echo "commit_changes=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Pick a branch name
        if: steps.check-changes.outputs.commit_changes == 'true'
        id: define-branch
        run: echo "branch=ci/update-system-tests-$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.check-changes.outputs.commit_changes == 'true'
        id: create-commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --message "feat(ci): Update system tests" .github/workflows/run-system-tests.yml
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      - name: Push changes
        uses: DataDog/commit-headless@1186485b788f57eedaaadb19919781698b4d262f # action/v1.0.0
        if: ${{ steps.check-changes.outputs.commit_changes == 'true' && steps.create-commit.outputs.commit != '' }}
        with:
          token: "${{ steps.octo-sts.outputs.token }}"
          branch: "${{ steps.define-branch.outputs.branch }}"
          # for scheduled runs, sha is the tip of the default branch
          # for dispatched runs, sha is the tip of the branch it was dispatched on
          branch-from: "${{ github.sha }}"
          command: push
          commits: "${{ steps.create-commit.outputs.commit }}"
      - name: Create pull request
        if: ${{ steps.check-changes.outputs.commit_changes == 'true' && steps.create-commit.outputs.commit != '' }}
        env:
          GH_TOKEN: "${{ steps.octo-sts.outputs.token }}"
        run: |
          gh pr create --title "Update system tests" \
            --base master \
            --head ${{ steps.define-branch.outputs.branch }} \
            --label "comp: tooling" \
            --label "type: enhancement" \
            --label "tag: no release notes" \
            --body "This PR updates system tests to commit: ${{ steps.system-test-ref.outputs.commit }}."
